//! Golden-vector conformance for `APEX-T0.5` (`common::apex::subsystem`).
//!
//! Loads `../readme/apex/APEX-SUBSYSTEM-COMPATIBILITY-GOLDEN-VECTORS-v1.json`
//! (self-generated by `bastion-harness`'s `apex_emit_manifest_cbor` bin,
//! never hand-typed) and independently re-decodes every vector through the
//! real encoder/decoder — this is cross-target re-verification, not a
//! restatement of the emission tool's own self-check.

use serde_json::Value as Json;
use veloren_common::apex::digest::{DigestDomainIdV1, digest_canonical_bytes_v1};
use veloren_common::apex::manifest::{ManifestDecodeLimitsV1, decode_manifest_v1, encode_manifest_v1};
use veloren_common::apex::subsystem::{CompatibilityProfileV1, CompatibilityRuleV1, SubsystemDescriptorV1};

fn limits() -> ManifestDecodeLimitsV1 {
    ManifestDecodeLimitsV1 {
        max_input_bytes: 1 << 16,
        max_depth: 8,
        max_nodes: 4096,
        max_array_items: 256,
        max_map_entries: 256,
        max_machine_text_bytes: 4096,
        max_byte_string_bytes: 4096,
    }
}

fn hex_to_bytes(s: &str) -> Vec<u8> { (0..s.len()).step_by(2).map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap()).collect() }

fn load_vectors() -> Json {
    let raw = std::fs::read_to_string("../readme/apex/APEX-SUBSYSTEM-COMPATIBILITY-GOLDEN-VECTORS-v1.json")
        .expect("golden vectors fixture present (run bastion-harness's apex_emit_manifest_cbor first)");
    serde_json::from_str(&raw).expect("fixture is valid JSON")
}

#[test]
fn descriptor_vector_round_trips_and_digest_matches() {
    let vectors = load_vectors();
    let d = &vectors["descriptor"];
    let bytes = hex_to_bytes(d["hex"].as_str().unwrap());
    let decoded: SubsystemDescriptorV1 = decode_manifest_v1(&bytes, &limits()).expect("descriptor vector decodes");
    let re_encoded = encode_manifest_v1(&decoded, &limits()).expect("descriptor vector re-encodes");
    assert_eq!(bytes, re_encoded, "descriptor vector is not a fixed point of decode->encode");

    let digest = digest_canonical_bytes_v1(DigestDomainIdV1::SubsystemDescriptor, &bytes, 1 << 20).unwrap();
    let expected_hex: String = digest.bytes.as_array().iter().map(|b| format!("{b:02x}")).collect();
    assert_eq!(expected_hex, d["digest_hex"].as_str().unwrap(), "descriptor digest mismatch");
}

#[test]
fn every_rule_vector_round_trips() {
    let vectors = load_vectors();
    let rules = vectors["rules"].as_array().expect("rules array present");
    assert!(!rules.is_empty(), "vector corpus must not be vacuous");
    for entry in rules {
        let name = entry["name"].as_str().unwrap();
        let bytes = hex_to_bytes(entry["hex"].as_str().unwrap());
        let decoded: CompatibilityRuleV1 = decode_manifest_v1(&bytes, &limits()).unwrap_or_else(|e| panic!("{name}: decode failed: {e:?}"));
        let re_encoded = encode_manifest_v1(&decoded, &limits()).unwrap_or_else(|e| panic!("{name}: re-encode failed: {e:?}"));
        assert_eq!(bytes, re_encoded, "{name}: not a fixed point of decode->encode");
    }
}

/// Non-vacuity: the corpus must actually cover every known
/// `CompatibilityRuleV1` variant name, not just "some" rules.
#[test]
fn rule_vectors_cover_every_known_variant() {
    let vectors = load_vectors();
    let names: Vec<&str> = vectors["rules"].as_array().unwrap().iter().map(|r| r["name"].as_str().unwrap()).collect();
    for expected in [
        "rule.exact",
        "rule.accept_set",
        "rule.accept_range",
        "rule.negotiated_capability",
        "rule.direct_transform",
        "rule.provenance_only",
        "rule.unknown_noncritical",
    ] {
        assert!(names.contains(&expected), "vector corpus is missing {expected}");
    }
}

#[test]
fn profile_vector_round_trips_and_digest_matches() {
    let vectors = load_vectors();
    let p = &vectors["profile"];
    let bytes = hex_to_bytes(p["hex"].as_str().unwrap());
    let decoded: CompatibilityProfileV1 = decode_manifest_v1(&bytes, &limits()).expect("profile vector decodes");
    let re_encoded = encode_manifest_v1(&decoded, &limits()).expect("profile vector re-encodes");
    assert_eq!(bytes, re_encoded, "profile vector is not a fixed point of decode->encode");
    assert_eq!(decoded.entries().len(), 3, "profile vector must declare exactly its 3 documented slots");

    let digest = digest_canonical_bytes_v1(DigestDomainIdV1::CompatibilityProfile, &bytes, 1 << 20).unwrap();
    let expected_hex: String = digest.bytes.as_array().iter().map(|b| format!("{b:02x}")).collect();
    assert_eq!(expected_hex, p["digest_hex"].as_str().unwrap(), "profile digest mismatch");
}

/// Mutation canary (spec section 6): flipping one byte of a committed
/// vector must break its own round-trip or digest match -- proves this
/// test suite is actually sensitive to the fixture's content, not
/// vacuously green regardless of what's in the file.
#[test]
fn mutating_a_vector_byte_breaks_its_digest_match() {
    let vectors = load_vectors();
    let mut bytes = hex_to_bytes(vectors["descriptor"]["hex"].as_str().unwrap());
    let last = bytes.len() - 1;
    bytes[last] ^= 0xff;
    let digest = digest_canonical_bytes_v1(DigestDomainIdV1::SubsystemDescriptor, &bytes, 1 << 20).unwrap();
    let mutated_hex: String = digest.bytes.as_array().iter().map(|b| format!("{b:02x}")).collect();
    assert_ne!(mutated_hex, vectors["descriptor"]["digest_hex"].as_str().unwrap(), "mutation canary did not bite");
}
