//! `APEX-T3.3.14`: frozen catalog of every send-shaped call site found by
//! the packet's own exact command (rg -n send_fallible|send_prepared|.prepare(|.send( server/src)
//! as of this row's inventory pass, each classified exactly once.
//! GENERATED -- do not hand-edit; regenerate the same way this catalog was
//! built (see the T3.3.14 commit message for the classification rules).
//!
//! Keyed by (file path relative to server/src/, exact trimmed matched line
//! text, 0-based occurrence index within that file), not line number --
//! immune to unrelated line-number drift elsewhere in the same file
//! (matching this program's own cite-by-symbol-not-line convention), and
//! the occurrence index disambiguates the rare case of the exact same
//! snippet appearing more than once in one file (confirmed real:
//! sys/subscription.rs has two identical CreateEntity lines).

use super::SendSiteClassV1::{
    self, GameSyncV1Migrated, LegacyMechanism, NotAClientSend, Ping, PostAuthCandidate, PreAuth, Terminal,
    V1EgressMechanism,
};

pub(super) const SEND_SITE_CATALOG: [(&str, &str, u32, SendSiteClassV1); 195] = [
    ("weather/tick.rs", "lazy_msg = Some(client.prepare(ServerGeneral::WeatherUpdate(", 0, PostAuthCandidate),
    ("weather/tick.rs", "lazy_msg.as_ref().map(|msg| client.send_prepared(msg));", 0, PostAuthCandidate),
    ("weather/tick.rs", "let _ = weather_tx.send((grid, lightning_cells, sim));", 0, NotAClientSend),
    ("weather/tick.rs", "client.send_fallible(ServerGeneral::LocalWindUpdate(weather.wind));", 0, PostAuthCandidate),
    ("chunk_generator.rs", "let _ = chunk_tx.send((key, payload));", 0, NotAClientSend),
    ("chunk_generator.rs", "generator.chunk_tx.send((a, Err(None))).unwrap();", 0, NotAClientSend),
    ("chunk_generator.rs", "generator.chunk_tx.send((b, Err(None))).unwrap();", 0, NotAClientSend),
    ("chunk_generator.rs", ".send((*key, Err(None)))", 0, NotAClientSend),
    ("login_provider.rs", "let _ = pending_s.send(Err(err));", 0, NotAClientSend),
    ("login_provider.rs", "let _ = pending_s.send(Self::query(srv, &username_or_token).await);", 0, NotAClientSend),
    ("login_provider.rs", "let _ = pending_s.send(Ok((username.to_string(), uuid)));", 0, NotAClientSend),
    ("pet.rs", "c.send_fallible(ServerGeneral::GroupUpdate(g));", 0, PostAuthCandidate),
    ("client.rs", "let prepared = self.prepare(msg);", 0, LegacyMechanism),
    ("client.rs", "self.send_prepared(&prepared)", 0, LegacyMechanism),
    ("client.rs", "ServerMsg::Info(m) => self.register_stream.lock().unwrap().send(m),", 0, LegacyMechanism),
    ("client.rs", "ServerMsg::Init(m) => self.register_stream.lock().unwrap().send(m),", 0, LegacyMechanism),
    ("client.rs", "ServerMsg::RegisterAnswer(m) => self.register_stream.lock().unwrap().send(m),", 0, LegacyMechanism),
    ("client.rs", "self.character_screen_stream.lock().unwrap().send(g)", 0, LegacyMechanism),
    ("client.rs", "self.in_game_stream.lock().unwrap().send(g)", 0, LegacyMechanism),
    ("client.rs", "self.terrain_stream.lock().unwrap().send(g)", 0, LegacyMechanism),
    ("client.rs", "| ServerGeneral::Notification(_) => self.general_stream.lock().unwrap().send(g),", 0, LegacyMechanism),
    ("client.rs", "ServerMsg::Ping(m) => self.ping_stream.lock().unwrap().send(m),", 0, LegacyMechanism),
    ("client.rs", "pub(crate) fn send_fallible<M: Into<ServerMsg>>(&self, msg: M) { let _ = self.send(msg); }", 0, LegacyMechanism),
    ("client.rs", "pub(crate) fn send_prepared(&self, msg: &PreparedMsg) -> Result<(), StreamError> {", 0, LegacyMechanism),
    ("client.rs", "SemanticStreamIdV1::Bootstrap => self.register_stream.send(frame_bytes),", 0, V1EgressMechanism),
    ("client.rs", "SemanticStreamIdV1::CharacterScreen => self.character_screen_stream.send(frame_bytes),", 0, V1EgressMechanism),
    ("client.rs", "SemanticStreamIdV1::InGame => self.in_game_stream.send(frame_bytes),", 0, V1EgressMechanism),
    ("client.rs", "SemanticStreamIdV1::General => self.general_stream.send(frame_bytes),", 0, V1EgressMechanism),
    ("client.rs", "SemanticStreamIdV1::Terrain => self.terrain_stream.send(frame_bytes),", 0, V1EgressMechanism),
    ("sys/semantic_egress.rs", "// a send can fail (`send_fallible` silently discards", 0, NotAClientSend),
    ("state_ext.rs", "client.send_fallible(ServerGeneral::CharacterSuccess);", 0, PostAuthCandidate),
    ("state_ext.rs", "client.send_fallible(ServerGeneral::SpectatorSuccess(spawn_point));", 0, PostAuthCandidate),
    ("state_ext.rs", "let _ = client.send(ServerGeneral::server_msg(", 0, PostAuthCandidate),
    ("state_ext.rs", "let _ = client.send(ServerGeneral::server_msg(", 1, PostAuthCandidate),
    ("state_ext.rs", "chat_exporter.send(exported_message);", 0, NotAClientSend),
    ("state_ext.rs", "client.send_fallible(ServerGeneral::ChatMsg(resolved_msg.clone()));", 0, PostAuthCandidate),
    ("state_ext.rs", "from_client.send_fallible(ServerGeneral::ChatMsg(resolved_msg.clone()));", 0, PostAuthCandidate),
    ("state_ext.rs", "to_client.send_fallible(ServerGeneral::ChatMsg(resolved_msg));", 0, PostAuthCandidate),
    ("state_ext.rs", "client.send_fallible(ServerGeneral::ChatMsg(", 0, PostAuthCandidate),
    ("state_ext.rs", "client.send_fallible(ServerGeneral::ChatMsg(resolved_msg.clone()));", 1, PostAuthCandidate),
    ("state_ext.rs", "client.send_fallible(ServerGeneral::ChatMsg(resolved_msg.clone()));", 2, PostAuthCandidate),
    ("state_ext.rs", "client.send_fallible(ServerGeneral::ChatMsg(resolved_msg.clone()));", 3, PostAuthCandidate),
    ("state_ext.rs", "client.send_fallible(ServerGeneral::ChatMsg(resolved_msg.clone()));", 4, PostAuthCandidate),
    ("state_ext.rs", "from_client.send_fallible(ServerGeneral::ChatMsg(resolved_msg.clone()));", 1, PostAuthCandidate),
    ("state_ext.rs", "to_client.send_fallible(ServerGeneral::ChatMsg(resolved_msg));", 1, PostAuthCandidate),
    ("state_ext.rs", "client.send_fallible(ServerGeneral::ChatMsg(resolved_msg.clone()));", 5, PostAuthCandidate),
    ("state_ext.rs", "client.send_fallible(ServerGeneral::ChatMsg(reply));", 0, PostAuthCandidate),
    ("state_ext.rs", "lazy_msg = Some(client.prepare(msg));", 0, PostAuthCandidate),
    ("state_ext.rs", "lazy_msg.as_ref().map(|msg| client.send_prepared(msg));", 0, PostAuthCandidate),
    ("state_ext.rs", "lazy_msg = Some(client.prepare(msg));", 1, PostAuthCandidate),
    ("state_ext.rs", "lazy_msg.as_ref().map(|msg| client.send_prepared(msg));", 1, PostAuthCandidate),
    ("state_ext.rs", "c.send_fallible(ServerGeneral::GroupUpdate(g));", 0, PostAuthCandidate),
    ("state_ext.rs", "client.send_fallible(ServerGeneral::SpectatePosition(pos));", 0, PostAuthCandidate),
    ("state_ext.rs", "client.send_fallible(ServerGeneral::ChatMsg(msg.clone()));", 0, PostAuthCandidate),
    ("cmd.rs", "client.prepare(ServerGeneral::TimeOfDay(", 0, PostAuthCandidate),
    ("cmd.rs", "let _ = client.send_prepared(&msg);", 0, PostAuthCandidate),
    ("cmd.rs", "client.prepare(ServerGeneral::TimeOfDay(", 1, PostAuthCandidate),
    ("cmd.rs", "let _ = client.send_prepared(&msg);", 1, PostAuthCandidate),
    ("events/trade.rs", "c.send_fallible(ServerGeneral::FinishedTrade(TradeResult::Declined));", 0, PostAuthCandidate),
    ("rtsim/mod.rs", "if let Err(err) = tx.send(self.state.data().clone()) {", 0, NotAClientSend),
    ("connection_handler.rs", "let _ = stop_sender.send(());", 0, NotAClientSend),
    ("connection_handler.rs", ".send(network);", 0, NotAClientSend),
    ("connection_handler.rs", "info_requester_sender.send(sender)?;", 0, NotAClientSend),
    ("connection_handler.rs", "register_stream.send(server_data.info)?;", 0, PreAuth),
    ("connection_handler.rs", "client_sender.send(client)?;", 0, NotAClientSend),
    ("connection_handler.rs", "let _ = stop_sender.send(());", 1, NotAClientSend),
    ("events/player.rs", "client.send_fallible(ServerGeneral::ExitInGameSuccess);", 0, PostAuthCandidate),
    ("events/player.rs", "client.send_fallible(ServerGeneral::SetPlayerEntity(possessee_uid));", 0, PostAuthCandidate),
    ("events/player.rs", "client.send_fallible(ServerGeneral::CompSync(comp_sync_package, update_counter));", 0, PostAuthCandidate),
    ("lib.rs", "let _ = sender.send(connection_handler::ServerInfoPacket {", 0, NotAClientSend),
    ("lib.rs", "client.send_fallible(msg);", 0, PostAuthCandidate),
    ("events/invite.rs", "client.send_fallible(ServerGeneral::server_msg(", 0, PostAuthCandidate),
    ("events/invite.rs", "client.send_fallible(ServerGeneral::FinishedTrade(", 0, PostAuthCandidate),
    ("events/invite.rs", "client.send_fallible(ServerGeneral::server_msg(", 1, PostAuthCandidate),
    ("events/invite.rs", "client.send_fallible(ServerGeneral::Invite {", 0, PostAuthCandidate),
    ("events/invite.rs", "client.send_fallible(ServerGeneral::server_msg(", 2, PostAuthCandidate),
    ("events/invite.rs", "client.send_fallible(ServerGeneral::InvitePending(invitee_uid));", 0, PostAuthCandidate),
    ("events/invite.rs", "c.send_fallible(ServerGeneral::GroupUpdate(g));", 0, PostAuthCandidate),
    ("events/invite.rs", "client.send_fallible(ServerGeneral::server_msg(", 3, PostAuthCandidate),
    ("events/invite.rs", "c.send(ServerGeneral::UpdatePendingTrade(", 0, PostAuthCandidate),
    ("events/invite.rs", ".map(|c| c.send(ServerGeneral::UpdatePendingTrade(id, trade, pricing)));", 0, PostAuthCandidate),
    ("events/invite.rs", "client.send_fallible(ServerGeneral::FinishedTrade(TradeResult::Declined));", 0, PostAuthCandidate),
    ("events/invite.rs", "client.send_fallible(ServerGeneral::InviteComplete {", 0, PostAuthCandidate),
    ("events/inventory_manip.rs", "client.send_fallible(", 0, PostAuthCandidate),
    ("events/inventory_manip.rs", "c.send_fallible(ServerGeneral::GroupInventoryUpdate(", 0, PostAuthCandidate),
    ("events/interaction.rs", "client.send_fallible(ServerGeneral::Dialogue(*sender_uid, dialogue));", 0, PostAuthCandidate),
    ("events/group_manip.rs", "client.send_fallible(ServerGeneral::server_msg(", 0, PostAuthCandidate),
    ("events/group_manip.rs", "client.send_fallible(ServerGeneral::server_msg(", 1, PostAuthCandidate),
    ("events/group_manip.rs", "client.send_fallible(ServerGeneral::MapMarker(", 0, PostAuthCandidate),
    ("events/group_manip.rs", "c.send_fallible(ServerGeneral::GroupUpdate(g));", 0, PostAuthCandidate),
    ("events/group_manip.rs", "client.send_fallible(ServerGeneral::server_msg(", 2, PostAuthCandidate),
    ("events/group_manip.rs", "general_stream.send_fallible(ServerGeneral::server_msg(", 0, PostAuthCandidate),
    ("events/group_manip.rs", "client.send_fallible(ServerGeneral::server_msg(", 3, PostAuthCandidate),
    ("events/group_manip.rs", "c.send_fallible(ServerGeneral::GroupUpdate(g));", 1, PostAuthCandidate),
    ("events/group_manip.rs", "client.send_fallible(ServerGeneral::server_msg(", 4, PostAuthCandidate),
    ("events/group_manip.rs", "client.send_fallible(ServerGeneral::server_msg(", 5, PostAuthCandidate),
    ("events/group_manip.rs", "client.send_fallible(ServerGeneral::server_msg(", 6, PostAuthCandidate),
    ("events/group_manip.rs", "client.send_fallible(ServerGeneral::server_msg(", 7, PostAuthCandidate),
    ("events/group_manip.rs", "client.send_fallible(ServerGeneral::server_msg(", 8, PostAuthCandidate),
    ("events/group_manip.rs", "c.send_fallible(ServerGeneral::GroupUpdate(g));", 2, PostAuthCandidate),
    ("events/group_manip.rs", "client.send_fallible(ServerGeneral::server_msg(", 9, PostAuthCandidate),
    ("events/group_manip.rs", "client.send_fallible(ServerGeneral::server_msg(", 10, PostAuthCandidate),
    ("events/group_manip.rs", "client.send_fallible(ServerGeneral::server_msg(", 11, PostAuthCandidate),
    ("events/group_manip.rs", "client.send_fallible(ServerGeneral::server_msg(", 12, PostAuthCandidate),
    ("events/entity_manipulation.rs", "client.send_fallible(ServerGeneral::Knockback(impulse));", 0, PostAuthCandidate),
    ("events/entity_manipulation.rs", "client.send_fallible(ServerGeneral::FinishedTrade(", 0, PostAuthCandidate),
    ("events/entity_manipulation.rs", "client.send_fallible(ServerGeneral::MapMarker(", 0, PostAuthCandidate),
    ("persistence/diesel_to_rusqlite.rs", "let mut stmt = transaction.prepare(\"", 0, NotAClientSend),
    ("persistence/character_loader.rs", "if let Err(e) = internal_tx.send(response) {", 0, NotAClientSend),
    ("persistence/character_loader.rs", ".send((entity, CharacterLoaderRequestKind::LoadCharacterList {", 0, NotAClientSend),
    ("persistence/character_loader.rs", ".send((entity, CharacterLoaderRequestKind::LoadCharacterData {", 0, NotAClientSend),
    ("events/entity_creation.rs", "c.send_fallible(ServerGeneral::GroupUpdate(g));", 0, PostAuthCandidate),
    ("events/information.rs", "client.send_fallible(msg);", 0, PostAuthCandidate),
    ("events/information.rs", "client.send_fallible(msg);", 1, PostAuthCandidate),
    ("events/information.rs", ".send(ServerGeneral::PluginData(buf))", 0, PostAuthCandidate),
    // APEX MERGE (T2.5.11 joins T3.3's frozen catalog): the typed
    // artifact-serving send, sibling of the legacy PluginData send above
    // and classified identically — post-auth, migration-eligible when the
    // .14b-e adoption families reach the events/information.rs family.
    (
        "events/information.rs",
        ".send(common_net::msg::ServerGeneral::PluginArtifactData(response))",
        0,
        PostAuthCandidate,
    ),
    ("persistence/character_updater.rs", ".send(CharacterUpdaterMessage::DatabaseBatchCompletion(batch_id))", 0, NotAClientSend),
    ("persistence/character_updater.rs", "if let Err(e) = response_tx.send(response) {", 0, NotAClientSend),
    ("persistence/character_updater.rs", "if let Err(e) = response_tx.send(response) {", 1, NotAClientSend),
    ("persistence/character_updater.rs", ".send(CharacterUpdaterAction::CreateCharacter {", 0, NotAClientSend),
    ("persistence/character_updater.rs", ".send(CharacterUpdaterAction::EditCharacter {", 0, NotAClientSend),
    ("persistence/character_updater.rs", ".send(CharacterUpdaterAction::BatchUpdate {", 0, NotAClientSend),
    ("persistence/character_updater.rs", ".send(CharacterUpdaterAction::DisconnectedSuccess)", 0, NotAClientSend),
    ("sys/invite_timeout.rs", "client.send_fallible(ServerGeneral::InviteComplete {", 0, PostAuthCandidate),
    ("sys/chunk_serialize.rs", "if let Err(e) = chunk_sender.send(SerializedChunk {", 0, NotAClientSend),
    ("sys/entity_sync.rs", "client.send_fallible(create_msg.clone());", 0, PostAuthCandidate),
    ("sys/entity_sync.rs", "client.send_fallible(ServerGeneral::DeleteEntity(uid));", 0, PostAuthCandidate),
    ("sys/entity_sync.rs", "// T3.3.05) never reach the lazy prepare/send_prepared machinery", 0, PostAuthCandidate),
    ("sys/entity_sync.rs", "client.prepare(ServerGeneral::EntitySync(entity_sync_package)),", 0, PostAuthCandidate),
    ("sys/entity_sync.rs", "client.prepare(ServerGeneral::CompSync(", 0, PostAuthCandidate),
    ("sys/entity_sync.rs", "let _ = client.send_prepared(&msg.0);", 0, PostAuthCandidate),
    ("sys/entity_sync.rs", "let _ = client.send_prepared(&msg.1);", 0, PostAuthCandidate),
    ("sys/entity_sync.rs", "client.send_fallible(comp_sync_msg);", 0, PostAuthCandidate),
    ("sys/entity_sync.rs", "client.send_fallible(msg);", 0, PostAuthCandidate),
    ("sys/entity_sync.rs", "client.send_fallible(msg);", 1, PostAuthCandidate),
    ("sys/entity_sync.rs", "client.send_fallible(ServerGeneral::DeleteEntity(*uid));", 0, PostAuthCandidate),
    ("sys/entity_sync.rs", "client.send_fallible(msg);", 2, PostAuthCandidate),
    ("sys/entity_sync.rs", "client.send_fallible(msg);", 3, PostAuthCandidate),
    ("sys/entity_sync.rs", "// to Legacy's own prepare/send_prepared byte-sharing --", 0, PostAuthCandidate),
    ("sys/entity_sync.rs", "let msg = tod_lazymsg.unwrap_or_else(|| client.prepare(tod_msg.clone()));", 0, PostAuthCandidate),
    ("sys/entity_sync.rs", "let _ = client.send_prepared(&msg);", 0, PostAuthCandidate),
    ("sys/chunk_send.rs", "&& client.send_prepared(&sc.msg).is_err()", 0, PostAuthCandidate),
    ("sys/msg/character_screen.rs", "client.send(ServerGeneral::server_msg(", 0, PostAuthCandidate),
    ("sys/msg/character_screen.rs", "client.send(ServerGeneral::server_msg(", 1, PostAuthCandidate),
    ("sys/msg/character_screen.rs", "client.send(ServerGeneral::CharacterDataLoadResult(Err(", 0, PostAuthCandidate),
    ("sys/msg/character_screen.rs", "client.send(ServerGeneral::CharacterDataLoadResult(Err(", 1, PostAuthCandidate),
    ("sys/msg/character_screen.rs", "client.send(ServerGeneral::CharacterDataLoadResult(Err(String::from(", 0, PostAuthCandidate),
    ("sys/msg/character_screen.rs", "client.send(ServerGeneral::CharacterActionError(format!(", 0, PostAuthCandidate),
    ("sys/msg/character_screen.rs", "client.send(ServerGeneral::CharacterActionError(error.to_string()))?;", 0, PostAuthCandidate),
    ("sys/msg/character_screen.rs", "client.send(ServerGeneral::CharacterActionError(format!(", 1, PostAuthCandidate),
    ("sys/msg/character_screen.rs", "client.send(ServerGeneral::CharacterActionError(error.to_string()))?;", 1, PostAuthCandidate),
    ("sys/server_info.rs", "if let Err(e) = sender.send(ServerInfo {", 0, NotAClientSend),
    ("sys/subscription.rs", "client.send_fallible(msg);", 0, PostAuthCandidate),
    ("sys/subscription.rs", "client.send_fallible(msg);", 1, PostAuthCandidate),
    ("sys/subscription.rs", "client.send_fallible(msg);", 2, PostAuthCandidate),
    ("sys/subscription.rs", "client.send_fallible(msg);", 3, PostAuthCandidate),
    ("sys/subscription.rs", "client.send_fallible(msg);", 4, PostAuthCandidate),
    ("sys/subscription.rs", "client.send_fallible(msg);", 5, PostAuthCandidate),
    ("sys/msg/general.rs", "client.send_fallible(ServerGeneral::ChatMsg(", 0, PostAuthCandidate),
    ("sys/msg/general.rs", "client.send_fallible(ServerGeneral::ChatMsg(", 1, PostAuthCandidate),
    ("sys/msg/gizmos.rs", "client.send_fallible(ServerGeneral::Gizmos(gizmos));", 0, PostAuthCandidate),
    ("sys/terrain.rs", "client.send_fallible(ServerGeneral::TerrainChunkUpdate {", 0, PostAuthCandidate),
    ("sys/msg/in_game.rs", "client.send(ServerGeneral::ExitInGameSuccess)?;", 0, PostAuthCandidate),
    ("sys/msg/in_game.rs", "client.send(ServerGeneral::SetViewDistance(clamped_vds.terrain))?;", 0, PostAuthCandidate),
    ("sys/msg/in_game.rs", "client.send(ServerGeneral::BastionDesignation {", 0, PostAuthCandidate),
    ("sys/msg/in_game.rs", "client.send(ServerGeneral::server_msg(", 0, PostAuthCandidate),
    ("sys/msg/in_game.rs", "client.send(ServerGeneral::server_msg(", 1, PostAuthCandidate),
    ("sys/msg/in_game.rs", "client.send(ServerGeneral::server_msg(", 2, PostAuthCandidate),
    ("sys/msg/in_game.rs", "client.send(ServerGeneral::BastionDesignation {", 1, PostAuthCandidate),
    ("sys/msg/in_game.rs", "client.send(ServerGeneral::BastionDesignation {", 2, PostAuthCandidate),
    ("sys/msg/in_game.rs", "client.send(ServerGeneral::server_msg(", 3, PostAuthCandidate),
    ("sys/msg/in_game.rs", "client.send(ServerGeneral::server_msg(", 4, PostAuthCandidate),
    ("sys/msg/in_game.rs", "client.send(ServerGeneral::BastionDesignationRemoved { region })?;", 0, PostAuthCandidate),
    ("sys/msg/in_game.rs", "client.send(ServerGeneral::server_msg(", 5, PostAuthCandidate),
    ("sys/msg/in_game.rs", "client.send(ServerGeneral::server_msg(", 6, PostAuthCandidate),
    ("sys/msg/in_game.rs", "client.send(ServerGeneral::server_msg(", 7, PostAuthCandidate),
    ("sys/msg/in_game.rs", "client.send(ServerGeneral::server_msg(", 8, PostAuthCandidate),
    ("sys/msg/in_game.rs", "client.send(ServerGeneral::BastionInspectInfo { target, payload });", 0, PostAuthCandidate),
    ("sys/waypoint.rs", "client.send_fallible(ServerGeneral::Notification(", 0, PostAuthCandidate),
    ("sys/terrain_sync.rs", "lazy_msg = Some(client.prepare(ServerGeneral::TerrainBlockUpdates(", 0, PostAuthCandidate),
    ("sys/terrain_sync.rs", "lazy_msg.as_ref().map(|msg| client.send_prepared(msg));", 0, PostAuthCandidate),
    ("sys/msg/network_events.rs", "let _ = client.send(ServerGeneral::Disconnect(", 0, Terminal),
    ("sys/msg/ping.rs", "PingMsg::Ping => client.send(PingMsg::Pong)?,", 0, Ping),
    ("sys/msg/ping.rs", "client.send_fallible(PingMsg::Ping);", 0, Ping),
    ("sys/msg/terrain.rs", "client.send(ServerGeneral::LodZoneUpdate {", 0, PostAuthCandidate),
    ("sys/msg/register.rs", "let _ = client.send(Err::<SessionAdmissionV1, _>(e));", 0, PreAuth),
    ("sys/msg/register.rs", "client.prepare(ServerGeneral::PlayerListUpdate(PlayerListUpdate::Add(", 0, PreAuth),
    ("sys/msg/register.rs", "let _ = client.send(Err::<SessionAdmissionV1, _>(RegisterError::InvalidCharacter));", 0, PreAuth),
    ("sys/msg/register.rs", "let _ = clients.get(admission.entity).map(|c| c.send(Err::<SessionAdmissionV1, _>(RegisterError::OlderAttemptSuperseded)));", 0, PreAuth),
    ("sys/msg/register.rs", "let _ = clients.get(admission.entity).map(|c| c.send(Err::<SessionAdmissionV1, _>(e)));", 0, PreAuth),
    ("sys/msg/register.rs", "let _ = old_client.send(ServerGeneral::Disconnect(DisconnectReason::Kicked(String::from(", 0, PreAuth),
    ("sys/msg/register.rs", "let _ = client.send_prepared(msg);", 0, PreAuth),
    ("sys/msg/register.rs", "if client.send(Ok::<_, RegisterError>(admitted)).is_err() {", 0, PreAuth),
    ("sys/msg/register.rs", "let _ = client.send(ServerGeneral::PlayerListUpdate(PlayerListUpdate::init_canonical(", 0, PreAuth),
    ("sys/msg/register.rs", "if !sent_v1 && client.send(game_sync).is_err() {", 0, GameSyncV1Migrated),
];
