//! Deterministic renderer-owned interior visibility snapshots.
//!
//! The production client currently exposes terrain and the ordinary Z-level
//! slice, but not the private room boxes generated by `world::site` or a
//! runtime room/portal graph. `ZLevelOnly` is therefore a first-class,
//! fail-closed capability rather than guessed room authority.

use std::{
    collections::{BTreeMap, BTreeSet, VecDeque},
    sync::Arc,
};

use crate::{DomainHashErrorV1, domain_hash_v1};

pub const INTERIOR_VISIBILITY_VERSION_V1: u16 = 1;
pub const MAX_INTERIOR_ROOMS_V1: usize = 1_024;
pub const MAX_INTERIOR_PORTALS_V1: usize = 4_096;
pub const MAX_INTERIOR_BYTES_V1: usize = 1_048_576;
pub const MAX_INTERIOR_COORDINATE_V1: i32 = 1_000_000;
const MAGIC_V1: &[u8; 8] = b"BINTRV01";
const SEALED_V1: u8 = 1;

pub type InteriorDigestV1 = [u8; 32];

#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
#[repr(u8)]
pub enum InteriorSourceCapabilityV1 {
    RoomPortalMetadata = 1,
    ZLevelOnly = 2,
}

impl TryFrom<u8> for InteriorSourceCapabilityV1 {
    type Error = InteriorVisibilityErrorV1;

    fn try_from(value: u8) -> Result<Self, Self::Error> {
        match value {
            1 => Ok(Self::RoomPortalMetadata),
            2 => Ok(Self::ZLevelOnly),
            _ => Err(InteriorVisibilityErrorV1::UnsupportedCapability(value)),
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
pub struct InteriorBoundsV1 {
    pub minimum: [i32; 3],
    pub maximum: [i32; 3],
}

impl InteriorBoundsV1 {
    pub fn validate(self) -> Result<(), InteriorVisibilityErrorV1> {
        for axis in 0..3 {
            if self.minimum[axis] > self.maximum[axis]
                || self.minimum[axis]
                    .checked_abs()
                    .is_none_or(|value| value > MAX_INTERIOR_COORDINATE_V1)
                || self.maximum[axis]
                    .checked_abs()
                    .is_none_or(|value| value > MAX_INTERIOR_COORDINATE_V1)
            {
                return Err(InteriorVisibilityErrorV1::InvalidBounds);
            }
        }
        Ok(())
    }

    #[must_use]
    pub const fn highest_z(self) -> i32 { self.maximum[2] }
}

#[derive(Clone, Debug, Eq, Ord, PartialEq, PartialOrd)]
pub struct InteriorRoomV1 {
    pub semantic_id: InteriorDigestV1,
    pub source_state_digest: InteriorDigestV1,
    pub bounds: InteriorBoundsV1,
    pub floor_minimum: i16,
    pub floor_maximum: i16,
    pub reveal_authorized: bool,
}

#[derive(Clone, Debug, Eq, Ord, PartialEq, PartialOrd)]
pub struct InteriorPortalV1 {
    pub semantic_id: InteriorDigestV1,
    pub source_state_digest: InteriorDigestV1,
    pub room_a: InteriorDigestV1,
    pub room_b: InteriorDigestV1,
    pub open: bool,
    pub reveal_authorized: bool,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct InteriorVisibilityInputV1 {
    pub presentation_generation: u64,
    pub visibility_sequence: u64,
    pub presentation_frame_digest: InteriorDigestV1,
    pub terrain_generation: InteriorDigestV1,
    pub camera_token: InteriorDigestV1,
    pub cutaway_policy_digest: InteriorDigestV1,
    pub source_capability: InteriorSourceCapabilityV1,
    pub selected_room: Option<InteriorDigestV1>,
    pub occupied_room: Option<InteriorDigestV1>,
    pub maximum_visible_z: i32,
    pub rooms: Vec<InteriorRoomV1>,
    pub portals: Vec<InteriorPortalV1>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct InteriorVisibilitySnapshotV1 {
    presentation_generation: u64,
    visibility_sequence: u64,
    presentation_frame_digest: InteriorDigestV1,
    terrain_generation: InteriorDigestV1,
    camera_token: InteriorDigestV1,
    cutaway_policy_digest: InteriorDigestV1,
    source_capability: InteriorSourceCapabilityV1,
    selected_room: Option<InteriorDigestV1>,
    occupied_room: Option<InteriorDigestV1>,
    maximum_visible_z: i32,
    rooms: Vec<InteriorRoomV1>,
    portals: Vec<InteriorPortalV1>,
    visible_rooms: Vec<InteriorDigestV1>,
    visible_floors: Vec<i16>,
    canonical_bytes: Vec<u8>,
    snapshot_digest: InteriorDigestV1,
}

#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
#[repr(u8)]
pub enum InteriorConsumerV1 {
    Terrain = 1,
    Figure = 2,
    Object = 3,
    Shadow = 4,
    Picking = 5,
    Capture = 6,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct InteriorSubjectV1 {
    pub consumer: InteriorConsumerV1,
    pub semantic_id: InteriorDigestV1,
    pub room_id: Option<InteriorDigestV1>,
    pub bounds: InteriorBoundsV1,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct InteriorVisibilityDecisionV1 {
    pub visible: bool,
    pub used_z_level_fallback: bool,
    pub snapshot_digest: InteriorDigestV1,
    pub presentation_generation: u64,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum InteriorVisibilityErrorV1 {
    UnsupportedVersion(u16),
    UnsupportedCapability(u8),
    InvalidMagic,
    UnsealedOrPartial,
    InvalidGeneration,
    InvalidDigest,
    InvalidBounds,
    InvalidFloorRange,
    InvalidRoom,
    InvalidPortal,
    MissingSelection,
    UnknownRoom(InteriorDigestV1),
    UnauthorizedRoom(InteriorDigestV1),
    DuplicateRoom(InteriorDigestV1),
    DuplicatePortal(InteriorDigestV1),
    TooManyRooms(usize),
    TooManyPortals(usize),
    NonCanonicalOrder,
    MalformedBoolean(u8),
    MalformedOptionalTag(u8),
    Truncated,
    TrailingBytes(usize),
    DigestMismatch,
    EncodedSizeExceeded(usize),
    AllocationFailure,
    SizeOverflow,
    StaleOrEqualGeneration {
        current: (u64, u64),
        offered: (u64, u64),
    },
    Hash(DomainHashErrorV1),
}

impl InteriorVisibilitySnapshotV1 {
    pub fn seal(mut input: InteriorVisibilityInputV1) -> Result<Self, InteriorVisibilityErrorV1> {
        validate_common(&input)?;
        input.rooms.sort_unstable_by_key(|room| room.semantic_id);
        input
            .portals
            .sort_unstable_by_key(|portal| portal.semantic_id);
        reject_duplicate_rooms(&input.rooms)?;
        reject_duplicate_portals(&input.portals)?;

        let (visible_rooms, visible_floors) = match input.source_capability {
            InteriorSourceCapabilityV1::RoomPortalMetadata => derive_exact_visibility(&input)?,
            InteriorSourceCapabilityV1::ZLevelOnly => {
                if !input.rooms.is_empty()
                    || !input.portals.is_empty()
                    || input.selected_room.is_some()
                    || input.occupied_room.is_some()
                {
                    return Err(InteriorVisibilityErrorV1::InvalidRoom);
                }
                (Vec::new(), Vec::new())
            },
        };

        let mut value = Self {
            presentation_generation: input.presentation_generation,
            visibility_sequence: input.visibility_sequence,
            presentation_frame_digest: input.presentation_frame_digest,
            terrain_generation: input.terrain_generation,
            camera_token: input.camera_token,
            cutaway_policy_digest: input.cutaway_policy_digest,
            source_capability: input.source_capability,
            selected_room: input.selected_room,
            occupied_room: input.occupied_room,
            maximum_visible_z: input.maximum_visible_z,
            rooms: input.rooms,
            portals: input.portals,
            visible_rooms,
            visible_floors,
            canonical_bytes: Vec::new(),
            snapshot_digest: [0; 32],
        };
        let payload = value.encode_payload()?;
        value.snapshot_digest = domain_hash_v1(
            "bastion/r1e/interior-visibility",
            INTERIOR_VISIBILITY_VERSION_V1,
            0,
            &payload,
        )
        .map_err(InteriorVisibilityErrorV1::Hash)?;
        value.canonical_bytes = value.encode_envelope(&payload)?;
        Ok(value)
    }

    #[must_use]
    pub const fn presentation_generation(&self) -> u64 { self.presentation_generation }

    #[must_use]
    pub const fn visibility_sequence(&self) -> u64 { self.visibility_sequence }

    #[must_use]
    pub const fn source_capability(&self) -> InteriorSourceCapabilityV1 { self.source_capability }

    #[must_use]
    pub const fn maximum_visible_z(&self) -> i32 { self.maximum_visible_z }

    #[must_use]
    pub fn rooms(&self) -> &[InteriorRoomV1] { &self.rooms }

    #[must_use]
    pub fn portals(&self) -> &[InteriorPortalV1] { &self.portals }

    #[must_use]
    pub fn visible_rooms(&self) -> &[InteriorDigestV1] { &self.visible_rooms }

    #[must_use]
    pub fn visible_floors(&self) -> &[i16] { &self.visible_floors }

    #[must_use]
    pub fn canonical_bytes(&self) -> &[u8] { &self.canonical_bytes }

    #[must_use]
    pub const fn snapshot_digest(&self) -> InteriorDigestV1 { self.snapshot_digest }

    pub fn decide(
        &self,
        subject: InteriorSubjectV1,
    ) -> Result<InteriorVisibilityDecisionV1, InteriorVisibilityErrorV1> {
        subject.bounds.validate()?;
        if subject.semantic_id == [0; 32] {
            return Err(InteriorVisibilityErrorV1::InvalidDigest);
        }
        let (visible, used_z_level_fallback) = match (self.source_capability, subject.room_id) {
            (InteriorSourceCapabilityV1::RoomPortalMetadata, Some(room_id)) => {
                if self
                    .rooms
                    .binary_search_by_key(&room_id, |room| room.semantic_id)
                    .is_err()
                {
                    return Err(InteriorVisibilityErrorV1::UnknownRoom(room_id));
                }
                (self.visible_rooms.binary_search(&room_id).is_ok(), false)
            },
            // Unknown/unlabelled structures and current production data use
            // the same conservative ordinary Z-slice across every consumer.
            (_, None) | (InteriorSourceCapabilityV1::ZLevelOnly, Some(_)) => {
                (subject.bounds.highest_z() <= self.maximum_visible_z, true)
            },
        };
        Ok(InteriorVisibilityDecisionV1 {
            visible,
            used_z_level_fallback,
            snapshot_digest: self.snapshot_digest,
            presentation_generation: self.presentation_generation,
        })
    }

    pub fn decode_exact(bytes: &[u8]) -> Result<Self, InteriorVisibilityErrorV1> {
        if bytes.len() > MAX_INTERIOR_BYTES_V1 {
            return Err(InteriorVisibilityErrorV1::EncodedSizeExceeded(bytes.len()));
        }
        let mut reader = ReaderV1::new(bytes);
        if reader.take(8)? != MAGIC_V1 {
            return Err(InteriorVisibilityErrorV1::InvalidMagic);
        }
        let version = reader.u16()?;
        if version != INTERIOR_VISIBILITY_VERSION_V1 {
            return Err(InteriorVisibilityErrorV1::UnsupportedVersion(version));
        }
        if reader.u8()? != SEALED_V1 {
            return Err(InteriorVisibilityErrorV1::UnsealedOrPartial);
        }
        if reader.u8()? != 0 {
            return Err(InteriorVisibilityErrorV1::NonCanonicalOrder);
        }
        let input = InteriorVisibilityInputV1 {
            presentation_generation: reader.u64()?,
            visibility_sequence: reader.u64()?,
            presentation_frame_digest: reader.digest()?,
            terrain_generation: reader.digest()?,
            camera_token: reader.digest()?,
            cutaway_policy_digest: reader.digest()?,
            source_capability: InteriorSourceCapabilityV1::try_from(reader.u8()?)?,
            selected_room: reader.optional_digest()?,
            occupied_room: reader.optional_digest()?,
            maximum_visible_z: reader.i32()?,
            rooms: read_rooms(&mut reader)?,
            portals: read_portals(&mut reader)?,
        };
        let visible_rooms = read_digests(&mut reader, MAX_INTERIOR_ROOMS_V1)?;
        let visible_floors = read_floors(&mut reader)?;
        let encoded_digest = reader.digest()?;
        if reader.remaining() != 0 {
            return Err(InteriorVisibilityErrorV1::TrailingBytes(reader.remaining()));
        }
        let rebuilt = Self::seal(input)?;
        if rebuilt.visible_rooms != visible_rooms
            || rebuilt.visible_floors != visible_floors
            || rebuilt.snapshot_digest != encoded_digest
            || rebuilt.canonical_bytes.as_slice() != bytes
        {
            return Err(InteriorVisibilityErrorV1::DigestMismatch);
        }
        Ok(rebuilt)
    }

    fn encode_payload(&self) -> Result<Vec<u8>, InteriorVisibilityErrorV1> {
        let mut output = Vec::new();
        output
            .try_reserve(320)
            .map_err(|_| InteriorVisibilityErrorV1::AllocationFailure)?;
        put_u64(&mut output, self.presentation_generation);
        put_u64(&mut output, self.visibility_sequence);
        output.extend_from_slice(&self.presentation_frame_digest);
        output.extend_from_slice(&self.terrain_generation);
        output.extend_from_slice(&self.camera_token);
        output.extend_from_slice(&self.cutaway_policy_digest);
        output.push(self.source_capability as u8);
        put_optional_digest(&mut output, self.selected_room);
        put_optional_digest(&mut output, self.occupied_room);
        put_i32(&mut output, self.maximum_visible_z);
        put_count(&mut output, self.rooms.len())?;
        for room in &self.rooms {
            encode_room(&mut output, room);
        }
        put_count(&mut output, self.portals.len())?;
        for portal in &self.portals {
            encode_portal(&mut output, portal);
        }
        put_count(&mut output, self.visible_rooms.len())?;
        for room in &self.visible_rooms {
            output.extend_from_slice(room);
        }
        put_count(&mut output, self.visible_floors.len())?;
        for floor in &self.visible_floors {
            output.extend_from_slice(&floor.to_le_bytes());
        }
        Ok(output)
    }

    fn encode_envelope(&self, payload: &[u8]) -> Result<Vec<u8>, InteriorVisibilityErrorV1> {
        let capacity = MAGIC_V1
            .len()
            .checked_add(4)
            .and_then(|value| value.checked_add(payload.len()))
            .and_then(|value| value.checked_add(32))
            .ok_or(InteriorVisibilityErrorV1::SizeOverflow)?;
        if capacity > MAX_INTERIOR_BYTES_V1 {
            return Err(InteriorVisibilityErrorV1::EncodedSizeExceeded(capacity));
        }
        let mut output = Vec::new();
        output
            .try_reserve_exact(capacity)
            .map_err(|_| InteriorVisibilityErrorV1::AllocationFailure)?;
        output.extend_from_slice(MAGIC_V1);
        output.extend_from_slice(&INTERIOR_VISIBILITY_VERSION_V1.to_le_bytes());
        output.push(SEALED_V1);
        output.push(0);
        output.extend_from_slice(payload);
        output.extend_from_slice(&self.snapshot_digest);
        Ok(output)
    }
}

#[derive(Debug, Default)]
pub struct InteriorVisibilityPublicationV1 {
    current: Option<Arc<InteriorVisibilitySnapshotV1>>,
}

impl InteriorVisibilityPublicationV1 {
    pub fn publish(
        &mut self,
        snapshot: InteriorVisibilitySnapshotV1,
    ) -> Result<Arc<InteriorVisibilitySnapshotV1>, InteriorVisibilityErrorV1> {
        let offered = (
            snapshot.presentation_generation,
            snapshot.visibility_sequence,
        );
        let current = self.current.as_ref().map_or((0, 0), |value| {
            (value.presentation_generation, value.visibility_sequence)
        });
        if offered <= current {
            return Err(InteriorVisibilityErrorV1::StaleOrEqualGeneration { current, offered });
        }
        let published = Arc::new(snapshot);
        self.current = Some(Arc::clone(&published));
        Ok(published)
    }

    #[must_use]
    pub fn acquire(&self) -> Option<Arc<InteriorVisibilitySnapshotV1>> { self.current.clone() }
}

fn validate_common(input: &InteriorVisibilityInputV1) -> Result<(), InteriorVisibilityErrorV1> {
    if input.presentation_generation == 0 || input.visibility_sequence == 0 {
        return Err(InteriorVisibilityErrorV1::InvalidGeneration);
    }
    if [
        input.presentation_frame_digest,
        input.terrain_generation,
        input.camera_token,
        input.cutaway_policy_digest,
    ]
    .contains(&[0; 32])
    {
        return Err(InteriorVisibilityErrorV1::InvalidDigest);
    }
    if input
        .maximum_visible_z
        .checked_abs()
        .is_none_or(|value| value > MAX_INTERIOR_COORDINATE_V1)
    {
        return Err(InteriorVisibilityErrorV1::InvalidBounds);
    }
    if input.rooms.len() > MAX_INTERIOR_ROOMS_V1 {
        return Err(InteriorVisibilityErrorV1::TooManyRooms(input.rooms.len()));
    }
    if input.portals.len() > MAX_INTERIOR_PORTALS_V1 {
        return Err(InteriorVisibilityErrorV1::TooManyPortals(
            input.portals.len(),
        ));
    }
    for room in &input.rooms {
        if room.semantic_id == [0; 32] || room.source_state_digest == [0; 32] {
            return Err(InteriorVisibilityErrorV1::InvalidRoom);
        }
        room.bounds.validate()?;
        if room.floor_minimum > room.floor_maximum {
            return Err(InteriorVisibilityErrorV1::InvalidFloorRange);
        }
    }
    for portal in &input.portals {
        if portal.semantic_id == [0; 32]
            || portal.source_state_digest == [0; 32]
            || portal.room_a == [0; 32]
            || portal.room_b == [0; 32]
            || portal.room_a == portal.room_b
        {
            return Err(InteriorVisibilityErrorV1::InvalidPortal);
        }
    }
    Ok(())
}

fn derive_exact_visibility(
    input: &InteriorVisibilityInputV1,
) -> Result<(Vec<InteriorDigestV1>, Vec<i16>), InteriorVisibilityErrorV1> {
    let rooms = input
        .rooms
        .iter()
        .map(|room| (room.semantic_id, room))
        .collect::<BTreeMap<_, _>>();
    let roots = [input.selected_room, input.occupied_room]
        .into_iter()
        .flatten()
        .collect::<BTreeSet<_>>();
    if roots.is_empty() {
        return Err(InteriorVisibilityErrorV1::MissingSelection);
    }
    for root in &roots {
        let room = rooms
            .get(root)
            .ok_or(InteriorVisibilityErrorV1::UnknownRoom(*root))?;
        if !room.reveal_authorized {
            return Err(InteriorVisibilityErrorV1::UnauthorizedRoom(*root));
        }
    }

    let mut adjacency = BTreeMap::<InteriorDigestV1, Vec<InteriorDigestV1>>::new();
    for portal in &input.portals {
        if !rooms.contains_key(&portal.room_a) {
            return Err(InteriorVisibilityErrorV1::UnknownRoom(portal.room_a));
        }
        if !rooms.contains_key(&portal.room_b) {
            return Err(InteriorVisibilityErrorV1::UnknownRoom(portal.room_b));
        }
        if portal.open && portal.reveal_authorized {
            adjacency
                .entry(portal.room_a)
                .or_default()
                .push(portal.room_b);
            adjacency
                .entry(portal.room_b)
                .or_default()
                .push(portal.room_a);
        }
    }
    for neighbors in adjacency.values_mut() {
        neighbors.sort_unstable();
        neighbors.dedup();
    }

    let mut visible = BTreeSet::new();
    let mut queue = VecDeque::new();
    queue.extend(roots);
    while let Some(room_id) = queue.pop_front() {
        let room = rooms
            .get(&room_id)
            .ok_or(InteriorVisibilityErrorV1::UnknownRoom(room_id))?;
        if !room.reveal_authorized || !visible.insert(room_id) {
            continue;
        }
        if let Some(neighbors) = adjacency.get(&room_id) {
            queue.extend(neighbors.iter().copied());
        }
    }

    let visible_rooms = visible.into_iter().collect::<Vec<_>>();
    let mut floors = BTreeSet::new();
    for room_id in &visible_rooms {
        let room = rooms
            .get(room_id)
            .ok_or(InteriorVisibilityErrorV1::UnknownRoom(*room_id))?;
        for floor in room.floor_minimum..=room.floor_maximum {
            floors.insert(floor);
            if floors.len() > MAX_INTERIOR_ROOMS_V1 {
                return Err(InteriorVisibilityErrorV1::InvalidFloorRange);
            }
        }
    }
    Ok((visible_rooms, floors.into_iter().collect()))
}

fn reject_duplicate_rooms(rooms: &[InteriorRoomV1]) -> Result<(), InteriorVisibilityErrorV1> {
    if let Some(pair) = rooms
        .windows(2)
        .find(|pair| pair[0].semantic_id == pair[1].semantic_id)
    {
        return Err(InteriorVisibilityErrorV1::DuplicateRoom(
            pair[0].semantic_id,
        ));
    }
    Ok(())
}

fn reject_duplicate_portals(portals: &[InteriorPortalV1]) -> Result<(), InteriorVisibilityErrorV1> {
    if let Some(pair) = portals
        .windows(2)
        .find(|pair| pair[0].semantic_id == pair[1].semantic_id)
    {
        return Err(InteriorVisibilityErrorV1::DuplicatePortal(
            pair[0].semantic_id,
        ));
    }
    Ok(())
}

fn put_optional_digest(output: &mut Vec<u8>, value: Option<InteriorDigestV1>) {
    match value {
        Some(value) => {
            output.push(1);
            output.extend_from_slice(&value);
        },
        None => output.push(0),
    }
}

fn put_u64(output: &mut Vec<u8>, value: u64) { output.extend_from_slice(&value.to_le_bytes()); }

fn put_i32(output: &mut Vec<u8>, value: i32) { output.extend_from_slice(&value.to_le_bytes()); }

fn put_count(output: &mut Vec<u8>, value: usize) -> Result<(), InteriorVisibilityErrorV1> {
    let value = u32::try_from(value).map_err(|_| InteriorVisibilityErrorV1::SizeOverflow)?;
    output.extend_from_slice(&value.to_le_bytes());
    Ok(())
}

fn encode_bounds(output: &mut Vec<u8>, bounds: InteriorBoundsV1) {
    for value in bounds.minimum.into_iter().chain(bounds.maximum) {
        put_i32(output, value);
    }
}

fn encode_room(output: &mut Vec<u8>, room: &InteriorRoomV1) {
    output.extend_from_slice(&room.semantic_id);
    output.extend_from_slice(&room.source_state_digest);
    encode_bounds(output, room.bounds);
    output.extend_from_slice(&room.floor_minimum.to_le_bytes());
    output.extend_from_slice(&room.floor_maximum.to_le_bytes());
    output.push(u8::from(room.reveal_authorized));
}

fn encode_portal(output: &mut Vec<u8>, portal: &InteriorPortalV1) {
    output.extend_from_slice(&portal.semantic_id);
    output.extend_from_slice(&portal.source_state_digest);
    output.extend_from_slice(&portal.room_a);
    output.extend_from_slice(&portal.room_b);
    output.push(u8::from(portal.open));
    output.push(u8::from(portal.reveal_authorized));
}

fn read_rooms(reader: &mut ReaderV1<'_>) -> Result<Vec<InteriorRoomV1>, InteriorVisibilityErrorV1> {
    let count = reader.count(MAX_INTERIOR_ROOMS_V1)?;
    let mut rooms = Vec::new();
    rooms
        .try_reserve_exact(count)
        .map_err(|_| InteriorVisibilityErrorV1::AllocationFailure)?;
    for _ in 0..count {
        rooms.push(InteriorRoomV1 {
            semantic_id: reader.digest()?,
            source_state_digest: reader.digest()?,
            bounds: reader.bounds()?,
            floor_minimum: reader.i16()?,
            floor_maximum: reader.i16()?,
            reveal_authorized: reader.boolean()?,
        });
    }
    Ok(rooms)
}

fn read_portals(
    reader: &mut ReaderV1<'_>,
) -> Result<Vec<InteriorPortalV1>, InteriorVisibilityErrorV1> {
    let count = reader.count(MAX_INTERIOR_PORTALS_V1)?;
    let mut portals = Vec::new();
    portals
        .try_reserve_exact(count)
        .map_err(|_| InteriorVisibilityErrorV1::AllocationFailure)?;
    for _ in 0..count {
        portals.push(InteriorPortalV1 {
            semantic_id: reader.digest()?,
            source_state_digest: reader.digest()?,
            room_a: reader.digest()?,
            room_b: reader.digest()?,
            open: reader.boolean()?,
            reveal_authorized: reader.boolean()?,
        });
    }
    Ok(portals)
}

fn read_digests(
    reader: &mut ReaderV1<'_>,
    maximum: usize,
) -> Result<Vec<InteriorDigestV1>, InteriorVisibilityErrorV1> {
    let count = reader.count(maximum)?;
    let mut values = Vec::new();
    values
        .try_reserve_exact(count)
        .map_err(|_| InteriorVisibilityErrorV1::AllocationFailure)?;
    for _ in 0..count {
        values.push(reader.digest()?);
    }
    Ok(values)
}

fn read_floors(reader: &mut ReaderV1<'_>) -> Result<Vec<i16>, InteriorVisibilityErrorV1> {
    let count = reader.count(MAX_INTERIOR_ROOMS_V1)?;
    let mut values = Vec::new();
    values
        .try_reserve_exact(count)
        .map_err(|_| InteriorVisibilityErrorV1::AllocationFailure)?;
    for _ in 0..count {
        values.push(reader.i16()?);
    }
    Ok(values)
}

struct ReaderV1<'a> {
    bytes: &'a [u8],
    cursor: usize,
}

impl<'a> ReaderV1<'a> {
    const fn new(bytes: &'a [u8]) -> Self { Self { bytes, cursor: 0 } }

    fn take(&mut self, count: usize) -> Result<&'a [u8], InteriorVisibilityErrorV1> {
        let end = self
            .cursor
            .checked_add(count)
            .ok_or(InteriorVisibilityErrorV1::Truncated)?;
        let value = self
            .bytes
            .get(self.cursor..end)
            .ok_or(InteriorVisibilityErrorV1::Truncated)?;
        self.cursor = end;
        Ok(value)
    }

    fn u8(&mut self) -> Result<u8, InteriorVisibilityErrorV1> {
        Ok(*self
            .take(1)?
            .first()
            .ok_or(InteriorVisibilityErrorV1::Truncated)?)
    }

    fn u16(&mut self) -> Result<u16, InteriorVisibilityErrorV1> {
        Ok(u16::from_le_bytes(
            self.take(2)?
                .try_into()
                .map_err(|_| InteriorVisibilityErrorV1::Truncated)?,
        ))
    }

    fn i16(&mut self) -> Result<i16, InteriorVisibilityErrorV1> {
        Ok(i16::from_le_bytes(
            self.take(2)?
                .try_into()
                .map_err(|_| InteriorVisibilityErrorV1::Truncated)?,
        ))
    }

    fn u32(&mut self) -> Result<u32, InteriorVisibilityErrorV1> {
        Ok(u32::from_le_bytes(
            self.take(4)?
                .try_into()
                .map_err(|_| InteriorVisibilityErrorV1::Truncated)?,
        ))
    }

    fn i32(&mut self) -> Result<i32, InteriorVisibilityErrorV1> {
        Ok(i32::from_le_bytes(
            self.take(4)?
                .try_into()
                .map_err(|_| InteriorVisibilityErrorV1::Truncated)?,
        ))
    }

    fn u64(&mut self) -> Result<u64, InteriorVisibilityErrorV1> {
        Ok(u64::from_le_bytes(
            self.take(8)?
                .try_into()
                .map_err(|_| InteriorVisibilityErrorV1::Truncated)?,
        ))
    }

    fn count(&mut self, maximum: usize) -> Result<usize, InteriorVisibilityErrorV1> {
        let count =
            usize::try_from(self.u32()?).map_err(|_| InteriorVisibilityErrorV1::SizeOverflow)?;
        if count > maximum {
            return Err(InteriorVisibilityErrorV1::EncodedSizeExceeded(count));
        }
        Ok(count)
    }

    fn digest(&mut self) -> Result<InteriorDigestV1, InteriorVisibilityErrorV1> {
        self.take(32)?
            .try_into()
            .map_err(|_| InteriorVisibilityErrorV1::Truncated)
    }

    fn optional_digest(&mut self) -> Result<Option<InteriorDigestV1>, InteriorVisibilityErrorV1> {
        match self.u8()? {
            0 => Ok(None),
            1 => Ok(Some(self.digest()?)),
            tag => Err(InteriorVisibilityErrorV1::MalformedOptionalTag(tag)),
        }
    }

    fn boolean(&mut self) -> Result<bool, InteriorVisibilityErrorV1> {
        match self.u8()? {
            0 => Ok(false),
            1 => Ok(true),
            value => Err(InteriorVisibilityErrorV1::MalformedBoolean(value)),
        }
    }

    fn bounds(&mut self) -> Result<InteriorBoundsV1, InteriorVisibilityErrorV1> {
        Ok(InteriorBoundsV1 {
            minimum: [self.i32()?, self.i32()?, self.i32()?],
            maximum: [self.i32()?, self.i32()?, self.i32()?],
        })
    }

    const fn remaining(&self) -> usize { self.bytes.len().saturating_sub(self.cursor) }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn digest(value: u8) -> InteriorDigestV1 { [value; 32] }

    fn hex_digest(value: InteriorDigestV1) -> String {
        value.iter().map(|byte| format!("{byte:02x}")).collect()
    }

    fn bounds(z_minimum: i32, z_maximum: i32) -> InteriorBoundsV1 {
        InteriorBoundsV1 {
            minimum: [-4, -4, z_minimum],
            maximum: [4, 4, z_maximum],
        }
    }

    fn room(id: u8, floor: i16, authorized: bool) -> InteriorRoomV1 {
        InteriorRoomV1 {
            semantic_id: digest(id),
            source_state_digest: digest(id + 20),
            bounds: bounds(i32::from(floor) * 4, i32::from(floor) * 4 + 3),
            floor_minimum: floor,
            floor_maximum: floor,
            reveal_authorized: authorized,
        }
    }

    fn portal(id: u8, a: u8, b: u8, open: bool, authorized: bool) -> InteriorPortalV1 {
        InteriorPortalV1 {
            semantic_id: digest(id),
            source_state_digest: digest(id + 20),
            room_a: digest(a),
            room_b: digest(b),
            open,
            reveal_authorized: authorized,
        }
    }

    fn exact_input() -> InteriorVisibilityInputV1 {
        InteriorVisibilityInputV1 {
            presentation_generation: 7,
            visibility_sequence: 1,
            presentation_frame_digest: digest(1),
            terrain_generation: digest(2),
            camera_token: digest(3),
            cutaway_policy_digest: digest(4),
            source_capability: InteriorSourceCapabilityV1::RoomPortalMetadata,
            selected_room: Some(digest(10)),
            occupied_room: Some(digest(10)),
            maximum_visible_z: 11,
            rooms: vec![
                room(12, 2, true),
                room(10, 0, true),
                room(11, 1, true),
                room(13, 3, false),
            ],
            portals: vec![
                portal(32, 12, 13, true, true),
                portal(30, 10, 11, true, true),
                portal(31, 11, 12, false, true),
            ],
        }
    }

    fn fallback_input() -> InteriorVisibilityInputV1 {
        InteriorVisibilityInputV1 {
            presentation_generation: 7,
            visibility_sequence: 1,
            presentation_frame_digest: digest(1),
            terrain_generation: digest(2),
            camera_token: digest(3),
            cutaway_policy_digest: digest(4),
            source_capability: InteriorSourceCapabilityV1::ZLevelOnly,
            selected_room: None,
            occupied_room: None,
            maximum_visible_z: 11,
            rooms: Vec::new(),
            portals: Vec::new(),
        }
    }

    #[test]
    fn canonical_order_and_frozen_vector_are_stable() {
        let first = InteriorVisibilitySnapshotV1::seal(exact_input()).unwrap();
        let mut permuted = exact_input();
        permuted.rooms.reverse();
        permuted.portals.reverse();
        let second = InteriorVisibilitySnapshotV1::seal(permuted).unwrap();
        assert_eq!(first.canonical_bytes(), second.canonical_bytes());
        assert_eq!(first.snapshot_digest(), second.snapshot_digest());
        assert_eq!(
            hex_digest(first.snapshot_digest()),
            "7fe9122c32159efa84c01afdd7e84553df1451184d01416a2b98468ef0cf6e4d"
        );
    }

    #[test]
    fn exact_decode_rejects_trailing_and_truncated_bytes() {
        let value = InteriorVisibilitySnapshotV1::seal(exact_input()).unwrap();
        assert_eq!(
            InteriorVisibilitySnapshotV1::decode_exact(value.canonical_bytes()).unwrap(),
            value
        );
        let mut trailing = value.canonical_bytes().to_vec();
        trailing.push(0);
        assert!(matches!(
            InteriorVisibilitySnapshotV1::decode_exact(&trailing),
            Err(InteriorVisibilityErrorV1::TrailingBytes(1))
        ));
        for length in 0..value.canonical_bytes().len() {
            assert!(
                InteriorVisibilitySnapshotV1::decode_exact(&value.canonical_bytes()[..length])
                    .is_err()
            );
        }
    }

    #[test]
    fn open_authorized_portals_define_visibility() {
        let value = InteriorVisibilitySnapshotV1::seal(exact_input()).unwrap();
        assert_eq!(value.visible_rooms(), &[digest(10), digest(11)]);
        assert_eq!(value.visible_floors(), &[0, 1]);
    }

    #[test]
    fn selected_and_occupied_rooms_are_both_visibility_roots() {
        let mut input = exact_input();
        input.occupied_room = Some(digest(12));
        let value = InteriorVisibilitySnapshotV1::seal(input).unwrap();
        assert_eq!(value.visible_rooms(), &[digest(10), digest(11), digest(12)]);
        assert_eq!(value.visible_floors(), &[0, 1, 2]);
    }

    #[test]
    fn closed_or_unauthorized_connections_do_not_reveal_rooms() {
        let mut input = exact_input();
        input.portals[2].open = true;
        input.portals[0].reveal_authorized = false;
        let value = InteriorVisibilitySnapshotV1::seal(input).unwrap();
        assert_eq!(value.visible_rooms(), &[digest(10), digest(11), digest(12)]);
        assert!(!value.visible_rooms().contains(&digest(13)));
    }

    #[test]
    fn invalid_metadata_fails_closed() {
        let mut duplicate = exact_input();
        duplicate.rooms.push(duplicate.rooms[0].clone());
        assert!(matches!(
            InteriorVisibilitySnapshotV1::seal(duplicate),
            Err(InteriorVisibilityErrorV1::DuplicateRoom(_))
        ));

        let mut missing = exact_input();
        missing.portals[0].room_b = digest(99);
        assert!(matches!(
            InteriorVisibilitySnapshotV1::seal(missing),
            Err(InteriorVisibilityErrorV1::UnknownRoom(id)) if id == digest(99)
        ));

        let mut unauthorized = exact_input();
        unauthorized.selected_room = Some(digest(13));
        assert!(matches!(
            InteriorVisibilitySnapshotV1::seal(unauthorized),
            Err(InteriorVisibilityErrorV1::UnauthorizedRoom(id)) if id == digest(13)
        ));

        let mut duplicate_portal = exact_input();
        duplicate_portal
            .portals
            .push(duplicate_portal.portals[0].clone());
        assert!(matches!(
            InteriorVisibilitySnapshotV1::seal(duplicate_portal),
            Err(InteriorVisibilityErrorV1::DuplicatePortal(_))
        ));
    }

    #[test]
    fn exact_room_decisions_hide_unreachable_rooms() {
        let value = InteriorVisibilitySnapshotV1::seal(exact_input()).unwrap();
        let visible = value
            .decide(InteriorSubjectV1 {
                consumer: InteriorConsumerV1::Figure,
                semantic_id: digest(80),
                room_id: Some(digest(11)),
                bounds: bounds(4, 7),
            })
            .unwrap();
        let hidden = value
            .decide(InteriorSubjectV1 {
                consumer: InteriorConsumerV1::Shadow,
                semantic_id: digest(81),
                room_id: Some(digest(12)),
                bounds: bounds(8, 11),
            })
            .unwrap();
        assert!(visible.visible);
        assert!(!visible.used_z_level_fallback);
        assert!(!hidden.visible);
        assert_eq!(visible.snapshot_digest, hidden.snapshot_digest);
    }

    #[test]
    fn fallback_cannot_self_claim_room_or_portal_authority() {
        let mut input = fallback_input();
        input.rooms.push(room(10, 0, true));
        assert!(matches!(
            InteriorVisibilitySnapshotV1::seal(input),
            Err(InteriorVisibilityErrorV1::InvalidRoom)
        ));
    }

    #[test]
    fn z_level_fallback_is_explicit_and_shared_by_every_consumer() {
        let value = InteriorVisibilitySnapshotV1::seal(fallback_input()).unwrap();
        for consumer in [
            InteriorConsumerV1::Terrain,
            InteriorConsumerV1::Figure,
            InteriorConsumerV1::Object,
            InteriorConsumerV1::Shadow,
            InteriorConsumerV1::Picking,
            InteriorConsumerV1::Capture,
        ] {
            let visible = value
                .decide(InteriorSubjectV1 {
                    consumer,
                    semantic_id: digest(50 + consumer as u8),
                    room_id: None,
                    bounds: bounds(7, 11),
                })
                .unwrap();
            assert!(visible.visible);
            assert!(visible.used_z_level_fallback);
            let hidden = value
                .decide(InteriorSubjectV1 {
                    consumer,
                    semantic_id: digest(70 + consumer as u8),
                    room_id: None,
                    bounds: bounds(12, 12),
                })
                .unwrap();
            assert!(!hidden.visible);
            assert_eq!(visible.snapshot_digest, hidden.snapshot_digest);
        }
    }

    #[test]
    fn unlabeled_subjects_use_z_fallback_with_room_metadata() {
        let value = InteriorVisibilitySnapshotV1::seal(exact_input()).unwrap();
        let decision = value
            .decide(InteriorSubjectV1 {
                consumer: InteriorConsumerV1::Object,
                semantic_id: digest(80),
                room_id: None,
                bounds: bounds(12, 12),
            })
            .unwrap();
        assert!(!decision.visible);
        assert!(decision.used_z_level_fallback);
    }

    #[test]
    fn publication_is_whole_immutable_and_monotonic() {
        let first = InteriorVisibilitySnapshotV1::seal(fallback_input()).unwrap();
        let first_digest = first.snapshot_digest();
        let mut publication = InteriorVisibilityPublicationV1::default();
        let held = publication.publish(first).unwrap();

        let mut second_input = fallback_input();
        second_input.visibility_sequence = 2;
        second_input.maximum_visible_z = 20;
        let second = publication
            .publish(InteriorVisibilitySnapshotV1::seal(second_input).unwrap())
            .unwrap();
        assert_eq!(held.snapshot_digest(), first_digest);
        assert_ne!(second.snapshot_digest(), first_digest);
        assert_eq!(
            publication.acquire().unwrap().snapshot_digest(),
            second.snapshot_digest()
        );

        let stale = InteriorVisibilitySnapshotV1::seal(fallback_input()).unwrap();
        assert!(matches!(
            publication.publish(stale),
            Err(InteriorVisibilityErrorV1::StaleOrEqualGeneration {
                current: (7, 2),
                offered: (7, 1)
            })
        ));
    }

    #[test]
    fn every_authority_field_changes_the_snapshot() {
        let baseline = InteriorVisibilitySnapshotV1::seal(exact_input())
            .unwrap()
            .snapshot_digest();
        let mut variants = Vec::new();
        let mut value = exact_input();
        value.presentation_generation += 1;
        variants.push(value);
        let mut value = exact_input();
        value.visibility_sequence += 1;
        variants.push(value);
        let mut value = exact_input();
        value.presentation_frame_digest = digest(60);
        variants.push(value);
        let mut value = exact_input();
        value.terrain_generation = digest(61);
        variants.push(value);
        let mut value = exact_input();
        value.camera_token = digest(62);
        variants.push(value);
        let mut value = exact_input();
        value.cutaway_policy_digest = digest(63);
        variants.push(value);
        let mut value = exact_input();
        value.maximum_visible_z += 1;
        variants.push(value);
        for variant in variants {
            assert_ne!(
                InteriorVisibilitySnapshotV1::seal(variant)
                    .unwrap()
                    .snapshot_digest(),
                baseline
            );
        }
    }
}
