//! `E14-4` — the determinism-scan baseline regeneration tool, as a
//! checked-in artifact rather than off-repo tooling. This module is the
//! PURE logic (parse an existing baseline file, diff it against a fresh
//! scan, decide append-safe vs refuse); `src/bin/determinism_scan_regen.rs`
//! is the thin CLI wrapper that reads the real tree and writes real files.
//!
//! **Why this exists.** Across `E13` chunks 1-4, the baseline files under
//! `common/src/determinism_scan_baseline_*.rs` were regenerated by a
//! script that ran only on its author's own machine — confirmed absent
//! from this repository (and from every gitignored path) during this
//! row's own cross-review. Two real incidents already happened because
//! of that: chunk 1's regeneration wrote to a MISNAMED file no
//! `include!` reads (`no_baseline_file_is_an_orphan` exists because of
//! it), and chunk 2's regeneration was caught (on a rebase, by a human
//! noticing six missing comment lines) almost blindly deleting a
//! builder's own annotation. "A builder ran something locally" is not a
//! fleet artifact; this row makes it one.
//!
//! **The clobber-guard, stated as the rule this module enforces.** A
//! baseline file's `//`-prefixed lines are NOT machine-owned — builders
//! annotate individual entries in place (`T4.6` chunk 3b did, explaining
//! a test-only poll loop; every `verified_notes` cross-reference in
//! `determinism_scan.rs` exists because a comment like this survived).
//! Regenerating that file must never require DELETING an existing
//! entry, because deleting an entry line risks deleting the annotation
//! sitting next to it, and a script cannot tell "this comment still
//! applies" from "this comment is now stale" — only a human can. So:
//! - If every change is an ADDITION (new live sites, no site vanished),
//!   apply it as a pure INSERT at the position sorted order calls for,
//!   touching no existing line — safe, done automatically.
//! - If ANY existing entry would need to be REMOVED (a site that was in
//!   the baseline is no longer live), REFUSE: write the fully
//!   regenerated content to a sibling `.new` file instead of touching
//!   the real one, and report exactly what would have been removed, so
//!   a human decides whether the comment beside it still applies.
//!
//! **The CRLF fix, folded in from the start rather than re-discovered.**
//! `E13` chunk 4 found the same off-repo tool false-positiving on CRLF
//! line endings — comparing a freshly-scanned line (LF, since the scan
//! itself reads via `fs::read_to_string` and matches on `.lines()`,
//! which splits on `\n` and leaves a dangling `\r` if the file is CRLF)
//! against an existing baseline line that had picked up CRLF from a
//! Windows checkout. Every comparison in this module strips trailing
//! `\r`/whitespace before comparing, once, here — not re-solved by
//! whoever reaches for this tool next.
//!
//! **Sort-position discipline.** `scanner_framework::scan_lines_matching`
//! itself sorts its output (`out.sort()`, over the `(file, snippet,
//! occurrence)` tuple) before returning it — the live scan's own
//! canonical order. New entries are inserted at the position that keeps
//! the file in that SAME order, not appended at the end, so a baseline
//! file's own ordering stays a property of its CONTENT rather than of
//! insertion history.

use std::collections::BTreeSet;

/// One line already sitting in an existing baseline file, tagged by
/// what it is -- the shape [`parse_baseline_file_v1`] produces and
/// [`regenerate_baseline_v1`] consumes.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum BaselineLineV1 {
    /// A `//`-prefixed comment line, kept byte-for-byte.
    Comment(String),
    /// A parsed `(file, snippet, occurrence)` tuple entry, plus its
    /// EXACT original source line (preserved verbatim on re-emission,
    /// including any trailing inline comment or formatting quirk) so
    /// re-emitting an untouched entry never rewrites it.
    Entry { key: (String, String, u32), raw: String },
    /// Blank line, kept for spacing.
    Blank,
}

/// Strips a trailing `\r` (CRLF survivor) and surrounding whitespace --
/// the one place this module's CRLF-insensitivity lives, per this
/// module's own doc comment.
fn normalize_line_v1(line: &str) -> &str { line.trim_end_matches('\r').trim() }

/// Parses a baseline file's raw text (the bracket-wrapped array literal
/// these files are, INCLUDING the leading `[` and trailing `]` lines,
/// which are dropped) into ordered [`BaselineLineV1`]s. A tuple line is
/// recognized by its own canonical shape (`("...", "...", N),`, quoted
/// Rust string literals, no attempt to parse a general Rust expression)
/// -- every existing baseline file in this repo is written in exactly
/// this shape, one entry per line, by construction (this module's own
/// job is to keep it that way).
pub fn parse_baseline_file_v1(content: &str) -> Vec<BaselineLineV1> {
    let mut out = Vec::new();
    for raw_line in content.lines() {
        let trimmed = normalize_line_v1(raw_line);
        if trimmed.is_empty() {
            out.push(BaselineLineV1::Blank);
            continue;
        }
        if trimmed == "[" || trimmed == "]" {
            continue;
        }
        if trimmed.starts_with("//") {
            out.push(BaselineLineV1::Comment(raw_line.trim_end_matches('\r').to_string()));
            continue;
        }
        if let Some(key) = parse_entry_line_v1(trimmed) {
            out.push(BaselineLineV1::Entry { key, raw: raw_line.trim_end_matches('\r').to_string() });
        }
        // A line that is none of the above (malformed) is silently
        // dropped rather than causing the whole parse to fail -- this
        // tool's job is to REGENERATE, not to be a strict Rust parser;
        // an unparseable line would show up as a spurious "removed"
        // entry downstream, which routes it to the refuse-and-.new path
        // for a human to look at rather than being silently lost.
    }
    out
}

/// Parses one `("file", "snippet", N),` line into its key. Returns
/// `None` if the line does not match this exact shape.
fn parse_entry_line_v1(line: &str) -> Option<(String, String, u32)> {
    let inner = line.trim_end();
    let inner = inner.strip_prefix('(')?;
    let inner = inner.trim_end();
    // The trailing `,` after the closing `)` is optional (the last entry
    // in a file may omit it), the closing `)` itself is not.
    let inner = inner.strip_suffix(',').unwrap_or(inner).trim_end();
    let inner = inner.strip_suffix(')')?;

    let rest = inner.strip_prefix('"')?;
    let file_end = rest.find('"')?;
    let file = &rest[..file_end];

    let after_file = &rest[file_end + 1..];
    let after_file = after_file.trim_start().strip_prefix(',')?.trim_start();
    let after_file = after_file.strip_prefix('"')?;

    // The snippet's closing quote is found via the `", ` boundary before
    // the trailing occurrence integer, not a bare last-quote search, so
    // a snippet containing an escaped quote doesn't fool the split
    // unless it also happens to be followed by `, ` inside its own text
    // (none of this repo's existing snippets are).
    let close = after_file.rfind("\", ")?;
    let snippet = &after_file[..close];
    let occurrence: u32 = after_file[close + 3..].trim().parse().ok()?;

    Some((unescape_v1(file), unescape_v1(snippet), occurrence))
}

/// Reverses the minimal escaping Rust string literals in these files
/// ever use (`\"` and `\\`) -- the scan itself never quotes anything
/// containing a literal backslash or quote in practice, but a snippet
/// line CAN contain `\"` if the scanned source itself does (e.g. a
/// format string), so this is not purely defensive.
fn unescape_v1(s: &str) -> String { s.replace("\\\"", "\"").replace("\\\\", "\\") }

/// Renders one live `(file, snippet, occurrence)` triple as a fresh
/// baseline line, matching [`scanner_framework::scan_lines_matching`]'s
/// own emitted shape.
fn render_entry_v1(key: &(String, String, u32)) -> String {
    format!(
        "    (\"{}\", \"{}\", {}),",
        key.0.replace('\\', "\\\\").replace('"', "\\\""),
        key.1.replace('\\', "\\\\").replace('"', "\\\""),
        key.2
    )
}

/// What regenerating one family's baseline against a fresh scan
/// resolves to.
#[derive(Debug, PartialEq, Eq)]
pub enum RegenOutcomeV1 {
    /// The live scan matches the existing baseline exactly -- nothing
    /// to do.
    Unchanged,
    /// Every live site is either already present or purely ADDITIVE --
    /// safe to apply automatically. `new_content` is the full,
    /// re-rendered file text (comments and existing entries preserved
    /// verbatim, new entries inserted at their sorted position).
    AppendedInPlace { added: Vec<(String, String, u32)>, new_content: String },
    /// At least one existing baseline entry has no live site anymore --
    /// REFUSED. `new_content` is what a full regeneration would produce
    /// (for the `.new` sibling file); `removed` names exactly what
    /// would be deleted, so a human can judge whether any comment beside
    /// those entries still applies.
    RefusedRemovalRequired { removed: Vec<(String, String, u32)>, new_content: String },
}

/// Detects which line ending a baseline file's raw text already uses,
/// so a regeneration writes the SAME convention back rather than
/// silently flipping it -- these files are checked out CRLF on this
/// repo's own Windows toolchain (confirmed directly against
/// `determinism_scan_baseline_instant.rs`'s on-disk bytes), and a
/// regen that emits bare `\n` would rewrite every untouched line's
/// ending, turning a genuinely additive change into a whole-file diff.
/// Exactly the `python-rewrites-flip-crlf` class of bug, reproduced
/// once already by this module's own first draft and caught before
/// commit -- see this module's own git history, not repeated here.
pub fn detect_line_ending_v1(content: &str) -> &'static str {
    if content.contains("\r\n") { "\r\n" } else { "\n" }
}

/// The core decision, pure: given an existing baseline file's parsed
/// lines and the live scan's current result, decide whether this is a
/// safe append or a refuse-and-`.new`, and produce the regenerated
/// content either way (the caller decides, based on the variant,
/// whether to write it to the real file or the `.new` sibling).
/// `line_ending` is normally [`detect_line_ending_v1`]'s own output on
/// the original file's raw text -- passed in rather than re-derived
/// here, since this function only sees the already-parsed
/// [`BaselineLineV1`]s.
pub fn regenerate_baseline_v1(
    existing: &[BaselineLineV1],
    live: &[(String, String, u32)],
    line_ending: &str,
) -> RegenOutcomeV1 {
    let existing_keys: BTreeSet<(String, String, u32)> =
        existing.iter().filter_map(|l| if let BaselineLineV1::Entry { key, .. } = l { Some(key.clone()) } else { None }).collect();
    let live_keys: BTreeSet<(String, String, u32)> = live.iter().cloned().collect();

    let added: Vec<(String, String, u32)> = live_keys.difference(&existing_keys).cloned().collect();
    let removed: Vec<(String, String, u32)> = existing_keys.difference(&live_keys).cloned().collect();

    if added.is_empty() && removed.is_empty() {
        return RegenOutcomeV1::Unchanged;
    }

    // Full regeneration: every EXISTING line (comments, blanks, and
    // entries still live) is kept verbatim and in place; entries no
    // longer live are dropped; new entries are inserted wherever sorted
    // order calls for them, relative to the surrounding entry lines
    // only (a comment's position relative to ITS OWN entry is
    // preserved, since comments are never reordered independently of
    // the entries adjacent to them in the source).
    let mut rendered: Vec<String> = Vec::new();
    let mut pending_new: Vec<&(String, String, u32)> = added.iter().collect();
    pending_new.sort();

    for line in existing {
        match line {
            BaselineLineV1::Entry { key, raw } => {
                if removed.contains(key) {
                    continue; // dropped -- named in RefusedRemovalRequired below
                }
                // Insert any pending new entries that sort BEFORE this
                // existing one, preserving overall sorted order.
                while let Some(&next) = pending_new.first() {
                    if next < key {
                        rendered.push(render_entry_v1(next));
                        pending_new.remove(0);
                    } else {
                        break;
                    }
                }
                rendered.push(raw.clone());
            },
            BaselineLineV1::Comment(c) => rendered.push(c.clone()),
            BaselineLineV1::Blank => rendered.push(String::new()),
        }
    }
    // Anything left over sorts after every existing entry.
    for next in pending_new {
        rendered.push(render_entry_v1(next));
    }

    let new_content = format!("[{le}{}{le}]{le}", rendered.join(line_ending), le = line_ending);

    if removed.is_empty() {
        RegenOutcomeV1::AppendedInPlace { added, new_content }
    } else {
        RegenOutcomeV1::RefusedRemovalRequired { removed, new_content }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn entry(file: &str, snippet: &str, occ: u32) -> (String, String, u32) { (file.to_string(), snippet.to_string(), occ) }

    #[test]
    fn parses_a_simple_baseline_file() {
        let content = "[\n    (\"a/b.rs\", \"Instant::now()\", 0),\n    (\"c/d.rs\", \"SystemTime::now()\", 1),\n]\n";
        let parsed = parse_baseline_file_v1(content);
        let entries: Vec<_> =
            parsed.iter().filter_map(|l| if let BaselineLineV1::Entry { key, .. } = l { Some(key.clone()) } else { None }).collect();
        assert_eq!(entries, vec![entry("a/b.rs", "Instant::now()", 0), entry("c/d.rs", "SystemTime::now()", 1)]);
    }

    #[test]
    fn preserves_comment_lines_through_the_parse() {
        let content = "[\n    // a builder's own note\n    (\"a/b.rs\", \"Instant::now()\", 0),\n]\n";
        let parsed = parse_baseline_file_v1(content);
        assert!(parsed.iter().any(|l| matches!(l, BaselineLineV1::Comment(c) if c.contains("a builder's own note"))));
    }

    #[test]
    fn crlf_line_endings_do_not_change_the_parsed_keys() {
        let lf = "[\n    (\"a/b.rs\", \"Instant::now()\", 0),\n]\n";
        let crlf = "[\r\n    (\"a/b.rs\", \"Instant::now()\", 0),\r\n]\r\n";
        let lf_entries: Vec<_> = parse_baseline_file_v1(lf)
            .into_iter()
            .filter_map(|l| if let BaselineLineV1::Entry { key, .. } = l { Some(key) } else { None })
            .collect();
        let crlf_entries: Vec<_> = parse_baseline_file_v1(crlf)
            .into_iter()
            .filter_map(|l| if let BaselineLineV1::Entry { key, .. } = l { Some(key) } else { None })
            .collect();
        assert_eq!(lf_entries, crlf_entries, "CRLF must not be treated as a content difference");
    }

    /// The row's own required falsifier: a CRLF-only baseline (every
    /// entry identical to the live scan except for line endings) must
    /// regenerate as `Unchanged`, not as a false clobber -- `E13` chunk
    /// 4's own bug, reproduced and proven fixed here.
    #[test]
    fn a_crlf_only_difference_regenerates_as_unchanged() {
        let crlf_existing = parse_baseline_file_v1("[\r\n    (\"a/b.rs\", \"Instant::now()\", 0),\r\n]\r\n");
        let live = vec![entry("a/b.rs", "Instant::now()", 0)];
        assert_eq!(regenerate_baseline_v1(&crlf_existing, &live, "\r\n"), RegenOutcomeV1::Unchanged);
    }

    #[test]
    fn no_change_when_live_matches_existing_exactly() {
        let existing = parse_baseline_file_v1("[\n    (\"a/b.rs\", \"Instant::now()\", 0),\n]\n");
        let live = vec![entry("a/b.rs", "Instant::now()", 0)];
        assert_eq!(regenerate_baseline_v1(&existing, &live, "\n"), RegenOutcomeV1::Unchanged);
    }

    /// The bug this row's first draft actually shipped, caught before
    /// commit: writing bare `\n` into a file this repo checks out CRLF
    /// turns a 19-line addition into an 83-line whole-file diff (every
    /// untouched line's ending "changes"). A regeneration must preserve
    /// the ORIGINAL file's line-ending convention on every line it
    /// re-emits, touched or not.
    #[test]
    fn an_additive_change_to_a_crlf_file_keeps_every_line_crlf() {
        let existing_src = "[\r\n    (\"a/b.rs\", \"Instant::now()\", 0),\r\n]\r\n";
        let existing = parse_baseline_file_v1(existing_src);
        let live = vec![entry("a/b.rs", "Instant::now()", 0), entry("z/new.rs", "SystemTime::now()", 0)];

        match regenerate_baseline_v1(&existing, &live, detect_line_ending_v1(existing_src)) {
            RegenOutcomeV1::AppendedInPlace { new_content, .. } => {
                assert!(
                    new_content.replace("\r\n", "").find('\n').is_none(),
                    "every \\n in the output must be part of a \\r\\n pair, got:\n{new_content:?}"
                );
                assert!(new_content.contains("(\"a/b.rs\", \"Instant::now()\", 0),\r\n"), "the untouched existing line must keep its CRLF ending:\n{new_content:?}");
                assert!(new_content.contains("(\"z/new.rs\", \"SystemTime::now()\", 0),\r\n"), "the new line must ALSO be CRLF, matching the file:\n{new_content:?}");
            },
            other => panic!("expected AppendedInPlace, got {other:?}"),
        }
    }

    /// The safe path: a purely additive change is applied automatically
    /// and does not touch any existing line -- checked by asserting the
    /// existing entry's raw source line appears byte-for-byte in the
    /// new content, not merely that its KEY is still present.
    #[test]
    fn a_purely_additive_change_is_appended_in_place_without_touching_existing_lines() {
        let existing_src = "[\n    // T4.6 chunk 3b's own annotation, must survive\n    (\"a/b.rs\", \"Instant::now()\", 0),\n]\n";
        let existing = parse_baseline_file_v1(existing_src);
        let live = vec![entry("a/b.rs", "Instant::now()", 0), entry("z/new.rs", "SystemTime::now()", 0)];

        match regenerate_baseline_v1(&existing, &live, "\n") {
            RegenOutcomeV1::AppendedInPlace { added, new_content } => {
                assert_eq!(added, vec![entry("z/new.rs", "SystemTime::now()", 0)]);
                assert!(
                    new_content.contains("// T4.6 chunk 3b's own annotation, must survive"),
                    "the existing annotation must survive verbatim:\n{new_content}"
                );
                assert!(new_content.contains("(\"a/b.rs\", \"Instant::now()\", 0),"), "the existing entry line must survive verbatim");
                assert!(new_content.contains("(\"z/new.rs\", \"SystemTime::now()\", 0),"), "the new entry must be added");
            },
            other => panic!("expected AppendedInPlace, got {other:?}"),
        }
    }

    /// The row's own named required test: the guard REFUSES when an
    /// annotated entry would need to be removed, rather than silently
    /// deleting the comment beside it.
    #[test]
    fn the_guard_refuses_when_an_annotated_entry_would_be_removed() {
        let existing_src = "[\n    // explains a test-only poll loop, T4.6 chunk 3b\n    (\"server/src/save_universe.rs\", \"let wait_deadline = ...;\", 0),\n]\n";
        let existing = parse_baseline_file_v1(existing_src);
        // The live scan no longer finds this site -- e.g. the poll loop
        // it annotated was refactored away.
        let live: Vec<(String, String, u32)> = vec![];

        match regenerate_baseline_v1(&existing, &live, "\n") {
            RegenOutcomeV1::RefusedRemovalRequired { removed, new_content } => {
                assert_eq!(removed, vec![entry("server/src/save_universe.rs", "let wait_deadline = ...;", 0)]);
                // The refusal's own `.new` content still carries the
                // comment -- nothing is silently dropped, a human just
                // has to look at it before it takes effect.
                assert!(new_content.contains("explains a test-only poll loop"));
            },
            other => panic!("expected RefusedRemovalRequired, got {other:?}"),
        }
    }

    /// A mix: one addition and one removal in the same regeneration
    /// must still refuse as a whole (the removal is the deciding
    /// factor), not silently apply the safe half.
    #[test]
    fn a_mixed_addition_and_removal_refuses_as_a_whole() {
        let existing = parse_baseline_file_v1("[\n    (\"a/b.rs\", \"Instant::now()\", 0),\n]\n");
        let live = vec![entry("z/new.rs", "SystemTime::now()", 0)];
        match regenerate_baseline_v1(&existing, &live, "\n") {
            RegenOutcomeV1::RefusedRemovalRequired { removed, .. } => {
                assert_eq!(removed, vec![entry("a/b.rs", "Instant::now()", 0)]);
            },
            other => panic!("expected RefusedRemovalRequired, got {other:?}"),
        }
    }

    /// Sort-position discipline: a new entry is inserted at the position
    /// sorted order calls for, not appended at the end -- matching
    /// `scanner_framework::scan_lines_matching`'s own `out.sort()`.
    #[test]
    fn new_entries_are_inserted_at_their_sorted_position_not_appended() {
        let existing = parse_baseline_file_v1("[\n    (\"a/first.rs\", \"Instant::now()\", 0),\n    (\"z/last.rs\", \"Instant::now()\", 0),\n]\n");
        // "m/middle.rs" sorts between the two existing entries.
        let live = vec![entry("a/first.rs", "Instant::now()", 0), entry("m/middle.rs", "Instant::now()", 0), entry("z/last.rs", "Instant::now()", 0)];

        match regenerate_baseline_v1(&existing, &live, "\n") {
            RegenOutcomeV1::AppendedInPlace { new_content, .. } => {
                let first_pos = new_content.find("a/first.rs").unwrap();
                let middle_pos = new_content.find("m/middle.rs").unwrap();
                let last_pos = new_content.find("z/last.rs").unwrap();
                assert!(first_pos < middle_pos && middle_pos < last_pos, "expected sorted insertion order, got:\n{new_content}");
            },
            other => panic!("expected AppendedInPlace, got {other:?}"),
        }
    }

    /// Non-vacuity: `FAMILIES`' own `baseline_file` fields actually name
    /// distinct, real filenames -- if this test ever fails, the regen
    /// tool's family-to-file mapping has drifted from what
    /// `determinism_scan.rs` itself declares.
    #[test]
    fn every_family_names_a_distinct_baseline_file() {
        use crate::determinism_scan::FAMILIES;
        let files: BTreeSet<&str> = FAMILIES.iter().map(|f| f.baseline_file).collect();
        assert_eq!(files.len(), FAMILIES.len(), "two families claim the same baseline_file");
        for family in FAMILIES {
            assert!(family.baseline_file.starts_with("determinism_scan_baseline_"), "{}: {}", family.name, family.baseline_file);
            assert!(family.baseline_file.ends_with(".rs"));
        }
    }
}
