[
    ("bastion-server/src/bastion_jobs.rs", "&& board.jobs.values().any(|j| {", 0),
    ("bastion-server/src/bastion_jobs.rs", "&& board.jobs.values().any(|j| {", 1),
    ("bastion-server/src/bastion_jobs.rs", ".keys()", 0),
    ("bastion-server/src/bastion_jobs.rs", ".values()", 0),
    ("bastion-server/src/bastion_jobs.rs", ".values()", 1),
    ("bastion-server/src/bastion_jobs.rs", ".values()", 2),
    ("bastion-server/src/bastion_jobs.rs", ".values()", 3),
    ("bastion-server/src/bastion_jobs.rs", ".values()", 4),
    ("bastion-server/src/bastion_jobs.rs", ".values()", 5),
    ("bastion-server/src/bastion_jobs.rs", ".values()", 6),
    ("bastion-server/src/bastion_jobs.rs", ".values()", 7),
    ("bastion-server/src/bastion_jobs.rs", ".values()", 8),
    ("bastion-server/src/bastion_jobs.rs", ".values()", 9),
    ("bastion-server/src/bastion_jobs.rs", ".values()", 10),
    ("bastion-server/src/bastion_jobs.rs", ".values()", 11),
    ("bastion-server/src/bastion_jobs.rs", ".values()", 12),
    ("bastion-server/src/bastion_jobs.rs", ".values()", 13),
    ("bastion-server/src/bastion_jobs.rs", ".values()", 14),
    ("bastion-server/src/bastion_jobs.rs", ".values()", 15),
    ("bastion-server/src/bastion_jobs.rs", ".values()", 16),
    ("bastion-server/src/bastion_jobs.rs", ".values()", 17),
    ("bastion-server/src/bastion_jobs.rs", ".values()", 18),
    ("bastion-server/src/bastion_jobs.rs", ".values()", 19),
    ("bastion-server/src/bastion_jobs.rs", ".values()", 20),
    ("bastion-server/src/bastion_jobs.rs", ".values_mut()", 0),
    ("bastion-server/src/bastion_jobs.rs", "/// `is_reserved` is O(1) instead of the linear `.values()` scan the", 0),
    ("bastion-server/src/bastion_jobs.rs", "board.jobs.values().filter(|job| job.is_access).count();", 0),
    ("bastion-server/src/bastion_jobs.rs", "board.jobs.values().map(|job| job.pos).collect();", 0),
    ("bastion-server/src/bastion_jobs.rs", "board.jobs.values().map(|j| j.pos).collect();", 0),
    ("bastion-server/src/bastion_jobs.rs", "board.jobs.values().map(|j| j.pos).collect();", 1),
    ("bastion-server/src/bastion_jobs.rs", "for item in reservations.values() {", 0),
    ("bastion-server/src/bastion_jobs.rs", "for job in board.jobs.values_mut() {", 0),
    ("bastion-server/src/bastion_jobs.rs", "for job in board.jobs.values_mut() {", 1),
    ("bastion-server/src/bastion_jobs.rs", "for job in board.jobs.values_mut() {", 2),
    ("bastion-server/src/bastion_jobs.rs", "for job in self.jobs.values() {", 0),
    ("bastion-server/src/bastion_jobs.rs", "for pos in board.beds.keys() {", 0),
    ("bastion-server/src/bastion_jobs.rs", "for pos in board.beds.keys() {", 1),
    ("bastion-server/src/bastion_jobs.rs", "for slot in board.beds.values_mut() {", 0),
    ("bastion-server/src/bastion_jobs.rs", "for slot in board.beds.values_mut() {", 1),
    ("bastion-server/src/bastion_jobs.rs", "let access_busy = board.jobs.values().any(|j| j.is_access);", 0),
    ("bastion-server/src/bastion_jobs.rs", "let access_jobs_exist = board.jobs.values().any(|j| j.is_access);", 0),
    ("bastion-server/src/bastion_jobs.rs", "let access_pending = board.jobs.values().any(|j| j.is_access);", 0),
    ("bastion-server/src/bastion_jobs.rs", "let gather_open = board.jobs.values().any(|j| {", 0),
    ("bastion-server/src/bastion_jobs.rs", "let mut ids = self.jobs.keys().copied().collect::<Vec<_>>();", 0),
    ("bastion-server/src/bastion_jobs.rs", "let occupied: HashSet<Vec3<i32>> = board.jobs.values().map(|j| j.pos).collect();", 0),
    ("bastion-server/src/bastion_jobs.rs", "let occupied: HashSet<Vec3<i32>> = board.jobs.values().map(|j| j.pos).collect();", 1),
    ("bastion-server/src/bastion_jobs.rs", "let occupied: HashSet<Vec3<i32>> = self.jobs.values().map(|j| j.pos).collect();", 0),
    ("bastion-server/src/bastion_jobs.rs", "let occupied: HashSet<Vec3<i32>> = self.jobs.values().map(|j| j.pos).collect();", 1),
    ("bastion-server/src/bastion_jobs.rs", "let occupied: HashSet<Vec3<i32>> = self.jobs.values().map(|j| j.pos).collect();", 2),
    ("bastion-server/src/bastion_jobs.rs", "let total = self.jobs.values().filter(|job| job.is_access).count();", 0),
    ("bastion-server/src/bastion_jobs.rs", "unavailable_cells.extend(board.emergency_access_cells.keys().copied());", 0),
    ("common/net/src/msg/checkpoint.rs", "let mut out: Vec<StagedRecordV1> = self.staged.values().cloned().collect();", 0),
    ("common/net/src/msg/checkpoint.rs", "let ordinals: Vec<CheckpointOrdinalV1> = self.staged.keys().map(|o| CheckpointOrdinalV1(*o)).collect();", 0),
    ("common/net/src/msg/command.rs", "if self.active.values().any(|e| e.descriptor.command_id == descriptor.command_id) {", 0),
    ("common/net/src/msg/command.rs", "self.active.keys().next_back().copied().unwrap_or(self.retired_floor).saturating_add(1)", 0),
    ("common/net/src/msg/compression.rs", ".and_then(|h| h.keys().next())", 0),
    ("common/src/astar.rs", "pub(crate) fn visited(&self) -> impl Iterator<Item = &S> { self.visited_nodes.keys() }", 0),
    ("common/src/async_schedule.rs", "self.classes.values().all(|class| class.backlog.is_empty())", 0),
    ("common/src/async_schedule.rs", "self.domains.values().all(|budget| budget.inner.is_empty())", 0),
    ("common/src/bin/find_unused.rs", "let mut recipes_to_check = recipes.keys().collect::<Vec<_>>();", 0),
    ("common/src/capability.rs", "for grant in self.grants.values() {", 0),
    ("common/src/causal_graph.rs", "for &start in self.nodes.keys() {", 0),
    ("common/src/cmd.rs", ".keys()", 0),
    ("common/src/cmd.rs", "config_spots.extend(SPOT_PARSER.keys().cloned());", 0),
    ("common/src/cmd.rs", "for kit in kits.0.values() {", 0),
    ("common/src/cmd.rs", "let mut buff_pack: Vec<String> = BUFF_PARSER.keys().cloned().collect();", 0),
    ("common/src/cmd.rs", "let mut buff_pack: Vec<_> = BUFF_PARSER.keys().cloned().collect();", 0),
    ("common/src/cmd.rs", "let mut kits = kits.read().0.keys().cloned().collect::<Vec<String>>();", 0),
    ("common/src/cmd.rs", "let mut preset_list: Vec<String> = PRESETS.keys().cloned().collect();", 0),
    ("common/src/cmd.rs", "rbm.keys().cloned().collect::<Vec<String>>()", 0),
    ("common/src/comp/aura.rs", "self.auras.values().flat_map(|i| i.iter().copied())", 0),
    ("common/src/comp/buff.rs", ".values()", 0),
    ("common/src/comp/buff.rs", ".values()", 1),
    ("common/src/comp/buff.rs", ".values()", 2),
    ("common/src/comp/buff.rs", ".values()", 3),
    ("common/src/comp/buff.rs", ".values()", 4),
    ("common/src/comp/buff.rs", ".values()", 5),
    ("common/src/comp/buff.rs", ".values()", 6),
    ("common/src/comp/buff.rs", "assert!(buff_comp.buffs.values().all(|b| b.start_time.0 < 50.01));", 0),
    ("common/src/comp/controller.rs", "// The SELECTED input (`.keys().next()` — what the state machine acts", 0),
    ("common/src/comp/controller.rs", "/// `queued_inputs.keys().next()` (the canonically-lowest InputKind — see", 0),
    ("common/src/comp/controller.rs", "assert_eq!(bwd.queued_inputs.keys().next(), Some(&Primary));", 0),
    ("common/src/comp/controller.rs", "assert_eq!(fwd.queued_inputs.keys().next(), Some(&Primary));", 0),
    ("common/src/comp/controller.rs", "assert_eq!(s1.queued_inputs.keys().next(), Some(&Secondary));", 0),
    ("common/src/comp/controller.rs", "assert_eq!(s2.queued_inputs.keys().next(), Some(&Block));", 0),
    ("common/src/comp/controller.rs", "assert_eq!(s3.queued_inputs.keys().next(), Some(&Ability(0)));", 0),
    ("common/src/comp/controller.rs", "let keys_bwd: Vec<InputKind> = bwd.queued_inputs.keys().copied().collect();", 0),
    ("common/src/comp/controller.rs", "let keys_fwd: Vec<InputKind> = fwd.queued_inputs.keys().copied().collect();", 0),
    ("common/src/comp/controller.rs", "s1.queued_inputs.keys().next(),", 0),
    ("common/src/comp/controller.rs", "s2.queued_inputs.keys().next()", 0),
    ("common/src/comp/inventory/item/mod.rs", ".keys()", 0),
    ("common/src/comp/inventory/item/mod.rs", ".values()", 0),
    ("common/src/comp/inventory/recipe_book.rs", ".keys()", 0),
    ("common/src/comp/skillset/mod.rs", ".keys()", 0),
    ("common/src/comp/skillset/mod.rs", "pub fn skill_groups(&self) -> impl Iterator<Item = &SkillGroup> { self.skill_groups.values() }", 0),
    ("common/src/content_manifest.rs", "for path in theirs.keys() {", 0),
    ("common/src/interaction.rs", "self.interactors.values()", 0),
    ("common/src/lottery.rs", "let total: u32 = forward.values().sum();", 0),
    ("common/src/mounting.rs", "self.riders.values().map(|link| link.rider)", 0),
    ("common/src/path.rs", "let mut candidates: Vec<_> = parents1.values().copied().collect();", 0),
    ("common/src/recipe.rs", "((input_max.values().sum::<u32>() as f32) / needed).floor() as u32;", 0),
    ("common/src/recipe.rs", "pub fn keys(&self) -> impl ExactSizeIterator<Item = &String> { self.recipes.keys() }", 0),
    ("common/src/region.rs", "self.regions.values_mut().for_each(|region| {", 0),
    ("common/src/rng_source_registry.rs", "// stacked hazards are closed: `touch_entities.keys()` is now", 0),
    ("common/src/rng_source_registry.rs", "let stale: Vec<&str> = registry.keys().copied().collect();", 0),
    ("common/src/run_equivalence.rs", ".chain(b.independent_events.keys())", 0),
    ("common/src/run_equivalence.rs", ".keys()", 0),
    ("common/src/run_equivalence.rs", "for key in a.conservation.keys().chain(b.conservation.keys()) {", 0),
    ("common/src/slowjob.rs", ".keys()", 0),
    ("common/src/slowjob.rs", "let order: Vec<String> = map.keys().cloned().collect();", 0),
    ("common/src/slowjob.rs", "let total_limit = queried_capped.values().sum::<u64>() as f32;", 0),
    ("common/src/states/utils.rs", "if data.controller.queued_inputs.keys().any(|i| i.is_ability()) {", 0),
    ("common/src/states/utils.rs", "if let Some(input) = data.controller.queued_inputs.keys().next() {", 0),
    ("common/src/states/utils.rs", "if let Some(input) = data.controller.queued_inputs.keys().next() {", 1),
    ("common/src/store.rs", "pub fn iter(&self) -> impl Iterator<Item = (Id<T>, &T)> { self.ids().zip(self.values()) }", 0),
    ("common/src/store.rs", "self.ids().zip(self.values_mut())", 0),
    ("common/src/terrain/structure.rs", "for sb in custom_indices.values() {", 0),
    ("common/src/util/spatial_grid.rs", "for cell in self.grid.values_mut() {", 0),
    ("common/src/util/spatial_grid.rs", "for cell in self.large_grid.values_mut() {", 0),
    // `E13` chunk 3, both BENIGN and read directly -- the two cases this
    // family's standing limit says it cannot tell apart, here told apart:
    //   manifest.rs: receiver is a `toml::value::Table`, which is a
    //   `BTreeMap` (the `toml` dep is v1 with `preserve_order` enabled
    //   NOWHERE in this workspace, checked) -- already canonically
    //   ordered, and the result is a diagnostic unknown-keys list.
    //   module.rs: `.keys()` is `.collect()`ed and then `sort_unstable()`
    //   on the VERY NEXT LINE, into a receipt input the doc itself calls
    //   "canonical sorted sets".
    // `E13` chunk 4 -- **NOT BENIGN. The first live hazard this family
    // has caught.** `touch_entities` is a real `hashbrown::HashMap<Uid,
    // Vec3<f32>>` (`common/src/comp/phys.rs:197`), and hashbrown's
    // default hasher is randomly seeded PER PROCESS, so this iteration
    // order differs between two runs of the same binary.
    //
    // Order alone would be survivable if the loop body were
    // commutative. It is not: the body draws `rng.random_bool(..)` PER
    // ITERATION (`buff.rs:186`) to decide whether fire spreads. A
    // different iteration order therefore hands the Nth draw to a
    // different entity -- so it is not the same set of entities catching
    // fire in a different order, it is a DIFFERENT SET catching fire.
    //
    // Compounding it, that `rng` is `rand::rng()` (`buff.rs:150`) --
    // thread-local OS entropy, not `combat::seed_ability_rng`, the
    // deterministic seam its siblings were migrated onto. Two
    // independent nondeterminism sources stacked in one loop.
    //
    // Left CLASSIFIED, not fixed: the fix is a behaviour change to fire
    // spread and belongs in its own reviewed row, not in a scan-root
    // widening. Flagged to the orchestrator as the campaign's top
    // buildable.
    ("common/state/src/plugin/manifest.rs", ".map(|t| t.keys().filter(|k| !known.contains(&k.as_str())).cloned().collect())", 0),
    ("common/state/src/plugin/module.rs", "let mut bodies: Vec<String> = store.data().registered_bodies.keys().cloned().collect();", 0),
    ("common/systems/src/buff.rs", "// `.keys()` order previously decided which touched", 0),
    ("common/systems/src/buff.rs", "physics_state.touch_entities.keys().copied().collect();", 0),
    ("rtsim/src/data/architect.rs", "pub fn total(&self) -> u32 { self.populations.values().sum::<u32>() }", 0),
    ("rtsim/src/data/npc.rs", "pub fn ids(&self) -> impl Iterator<Item = MountId> + '_ { self.links.keys() }", 0),
    ("rtsim/src/data/npc.rs", "pub fn iter(&self) -> impl Iterator<Item = &NpcLink> + '_ { self.links.values() }", 0),
    ("rtsim/src/data/npc.rs", "pub fn iter_mounts(&self) -> impl Iterator<Item = NpcId> + '_ { self.mount_map.keys() }", 0),
    ("rtsim/src/rule/migrate.rs", "for npc in data.npcs.values() {", 0),
    ("rtsim/src/rule/migrate.rs", "if !data.sites.values().any(|site| {", 0),
    ("rtsim/src/rule/npc_ai/mod.rs", "&& let Some((bar_pos, room_center)) = tavern.rooms.values().flat_map(|room|", 0),
    ("rtsim/src/rule/npc_ai/mod.rs", ".values()", 0),
    ("rtsim/src/rule/npc_ai/mod.rs", ".values()", 1),
    ("rtsim/src/rule/npc_ai/mod.rs", ".values()", 2),
    ("rtsim/src/rule/npc_ai/mod.rs", "let chair_pos = tavern.rooms.values().flat_map(|room| {", 0),
    ("server/src/chunk_generator.rs", "let held: Vec<Vec2<i32>> = self.arrived.keys().copied().collect();", 0),
    ("server/src/chunk_generator.rs", "self.pending_chunks.keys().copied()", 0),
    ("server/src/cmd.rs", ".values()", 0),
    ("server/src/cmd.rs", ".values()", 1),
    ("server/src/cmd.rs", ".values()", 2),
    ("server/src/cmd.rs", ".values()", 3),
    ("server/src/events/entity_manipulation.rs", ".values_mut()", 0),
    ("server/src/events/entity_manipulation.rs", ".values_mut()", 1),
    ("server/src/lib.rs", ".values()", 0),
    ("server/src/lib.rs", ".values()", 1),
    ("server/src/lib.rs", ".values()", 2),
    ("server/src/lib.rs", ".values()", 3),
    ("server/src/lib.rs", ".values()", 4),
    ("server/src/lib.rs", ".values()", 5),
    ("server/src/lib.rs", ".values()", 6),
    ("server/src/lib.rs", ".values()", 7),
    ("server/src/lib.rs", ".values()", 8),
    ("server/src/lib.rs", ".values()", 9),
    ("server/src/lib.rs", "for cells in cells_by_owner.values_mut() {", 0),
    ("server/src/lib.rs", "for j in board.jobs.values() {", 0),
    ("server/src/location.rs", "pub fn iter(&self) -> impl Iterator<Item = &String> { self.locations.keys() }", 0),
    ("server/src/physics_cohort.rs", ".values()", 0),
    ("server/src/rtsim/mod.rs", ".values()", 0),
    ("server/src/save_inventory.rs", "after.keys().collect::<Vec<_>>(),", 0),
    ("server/src/save_inventory.rs", "before.keys().collect::<Vec<_>>(),", 0),
    ("server/src/session_registry.rs", "fn active_count(&self) -> usize { self.records.values().filter(|r| matches!(r.state, SessionStateV1::Active)).count() }", 0),
    ("server/src/settings/server_description.rs", ".keys()", 0),
    ("server/src/sys/msg/in_game.rs", ".values()", 0),
    ("server/src/sys/msg/in_game.rs", ".values()", 1),
    ("server/src/terrain_persistence.rs", "let mut keys = self.chunks.keys().copied().collect::<Vec<_>>();", 0),
    ("world/src/civ/airship_travel.rs", ".keys()", 0),
    ("world/src/civ/airship_travel.rs", "// vertices in canonical order. `graph.keys()` yields nodes in hash order,", 0),
    ("world/src/civ/airship_travel.rs", "let mut graph_keys = graph.keys().copied().collect::<Vec<_>>();", 0),
    ("world/src/civ/mod.rs", ".values()", 0),
    ("world/src/civ/mod.rs", "/// `.keys()` iteration is already reproducible run-to-run for a fixed", 0),
    ("world/src/civ/mod.rs", "for sim_site in this.sites.values_mut() {", 0),
    ("world/src/civ/mod.rs", "let to = track_map.get(&site).map(|dests| dests.keys()).into_iter().flatten();", 0),
    ("world/src/civ/mod.rs", "pub fn sites(&self) -> impl Iterator<Item = &Site> + '_ { self.sites.values() }", 0),
    ("world/src/lib.rs", ".values()", 0),
    ("world/src/site/economy/context.rs", "&& let Some(site) = index.sites.values().find(|s| s.do_economic_simulation())", 0),
    ("world/src/site/economy/context.rs", "//     for site in index.sites.values() {", 0),
    ("world/src/site/economy/context.rs", "//     for v in index.trade.deliveries.values() {", 0),
    ("world/src/site/economy/context.rs", "for i in index.sites.values() {", 0),
    ("world/src/site/mod.rs", ".values()", 0),
    ("world/src/site/mod.rs", "pub fn any_plot<F: FnMut(&Plot) -> bool>(&self, f: F) -> bool { self.plots.values().any(f) }", 0),
    ("world/src/site/mod.rs", "pub fn plots(&self) -> impl ExactSizeIterator<Item = &Plot> + '_ { self.plots.values() }", 0),
    ("world/src/site/mod.rs", "self.plots.values().filter(move |p| f(p))", 0),
    ("world/src/site/plot/gnarling.rs", "if !parents.values().any(|e| e == &node_id) && node_id != 0 && node_id != last {", 0),
    ("world/src/site/plot/plaza.rs", "let any_water = center.water() || corner_meta.values().any(|c| c.water());", 0),
    ("world/src/site/plot/tavern.rs", ".chain(rooms[to_room].walls.values())", 0),
    ("world/src/site/plot/tavern.rs", ".values()", 0),
    ("world/src/site/plot/tavern.rs", "for roof in self.roofs.values() {", 0),
    ("world/src/site/plot/tavern.rs", "for roof in self.roofs.values() {", 1),
    ("world/src/site/plot/tavern.rs", "for room in rooms.values() {", 0),
    ("world/src/site/plot/tavern.rs", "for room in rooms.values_mut() {", 0),
    ("world/src/site/plot/tavern.rs", "for room in rooms.values_mut() {", 1),
    ("world/src/site/plot/tavern.rs", "for room in self.rooms.values() {", 0),
    ("world/src/site/plot/tavern.rs", "for room in self.rooms.values() {", 1),
    ("world/src/site/plot/tavern.rs", "for wall in self.walls.values() {", 0),
    ("world/src/site/plot/tavern.rs", "for wall in self.walls.values() {", 1),
    ("world/src/util/gen_cache.rs", "self.cache.values().filter_map(|v| v.as_ref())", 0),
]
