[
    ("bastion-server/src/bastion_flight_recorder.rs", "SystemTime::now()", 0),
    ("common/src/clock.rs", "last_tick: Instant::now(),", 0),
    ("common/src/clock.rs", "last_work: Instant::now(),", 0),
    ("common/src/clock.rs", "let this_tick = Instant::now();", 0),
    ("common/src/clock.rs", "self.last_work = Instant::now();", 0),
    ("common/src/comp/chat.rs", "let timeout = Instant::now() + Duration::from_secs_f64(SpeechBubble::DEFAULT_DURATION);", 0),
    ("common/src/comp/presence.rs", "let now = Instant::now();", 0),
    ("common/src/slowjob.rs", "let execution_end = Instant::now();", 0),
    ("common/src/slowjob.rs", "let execution_start = Instant::now();", 0),
    ("common/src/slowjob.rs", "let queue_created = Instant::now();", 0),
    ("common/src/slowjob.rs", "let start = Instant::now();", 0),
    ("server/src/chunk_generator.rs", "if std::time::Instant::now() > deadline {", 0),
    ("server/src/chunk_generator.rs", "let deadline = std::time::Instant::now() + std::time::Duration::from_secs(180);", 0),
    ("server/src/events/player.rs", "let now = std::time::Instant::now();", 0),
    ("server/src/events/player.rs", "std::time::Instant::now(),", 0),
    ("server/src/lib.rs", "let before_entity_cleanup = Instant::now();", 0),
    ("server/src/lib.rs", "let before_handle_events = Instant::now();", 0),
    ("server/src/lib.rs", "let before_new_connections = Instant::now();", 0),
    ("server/src/lib.rs", "let before_persistence_updates = Instant::now();", 0),
    ("server/src/lib.rs", "let before_state_tick = Instant::now();", 0),
    ("server/src/lib.rs", "let before_sync = Instant::now();", 0),
    ("server/src/lib.rs", "let before_update_terrain_and_regions = Instant::now();", 0),
    ("server/src/lib.rs", "let before_world_tick = Instant::now();", 0),
    ("server/src/lib.rs", "let end_of_server_tick = Instant::now();", 0),
    ("server/src/lib.rs", "self.state.ecs().write_resource::<TickStart>().0 = Instant::now();", 0),
    ("server/src/lib.rs", "state.ecs_mut().insert(TickStart(Instant::now()));", 0),
    ("server/src/metrics.rs", "let since_the_epoch = SystemTime::now()", 0),
    ("server/src/rtsim/mod.rs", "self.last_saved = Some(Instant::now());", 0),
    ("server/src/session_registry.rs", "fn now() -> Instant { Instant::now() }", 0),
    ("server/src/state_ext.rs", "Instant::now(),", 0),
    ("server/src/sys/invite_timeout.rs", "// not wall-clock Instant::now().", 0),
    ("server/src/sys/metrics.rs", "let start = Instant::now();", 0),
    ("server/src/sys/mod.rs", "last_run: Instant::now(),", 0),
    ("server/src/sys/mod.rs", "last_run: Instant::now(),", 1),
    ("server/src/sys/mod.rs", "self.last_run = Instant::now();", 0),
    ("server/src/sys/msg/in_game.rs", "let time_for_vd_changes = Instant::now();", 0),
    ("server/src/sys/msg/register.rs", "let outcomes = session_registry.admit_sorted(intents, max_players, Instant::now(), DEFAULT_DETACHED_RETENTION_CAP, &mut random_source);", 0),
    ("server/src/sys/semantic_egress.rs", "let out = registry.admit_sorted(vec![((), intent)], 64, std::time::Instant::now(), 64, &mut src);", 0),
    ("server/src/sys/semantic_egress.rs", "registry.detach(recipient.session_id, std::time::Instant::now(), std::time::Duration::from_secs(60), 64);", 0),
    ("world/src/sim/erosion.rs", "let start_time = Instant::now();", 0),
    ("world/src/sim/erosion.rs", "let start_time = Instant::now();", 1),
    ("world/src/sim/erosion.rs", "let start_time = Instant::now();", 2),
    ("world/src/sim/erosion.rs", "let start_time = Instant::now();", 3),
    ("world/src/sim/mod.rs", "let now = std::time::Instant::now();", 0),
]
